In [1]:
import polars as pl
from config import data_cfg

In [2]:
data=pl.read_parquet(data_cfg["train"])

In [3]:
data.head()

shape: (5, 10)
┌────────┬─────────┬────────┬───────────┬───┬────────────┬─────────┬───────────────┬───────────────┐
│ userId ┆ movieId ┆ rating ┆ timestamp ┆ … ┆ occupation ┆ zipCode ┆ title         ┆ genres        │
│ ---    ┆ ---     ┆ ---    ┆ ---       ┆   ┆ ---        ┆ ---     ┆ ---           ┆ ---           │
│ i32    ┆ i32     ┆ i32    ┆ i64       ┆   ┆ i32        ┆ str     ┆ str           ┆ str           │
╞════════╪═════════╪════════╪═══════════╪═══╪════════════╪═════════╪═══════════════╪═══════════════╡
│ 1492   ┆ 1923    ┆ 4      ┆ 974750318 ┆ … ┆ 12         ┆ 98102   ┆ There's       ┆ Comedy        │
│        ┆         ┆        ┆           ┆   ┆            ┆         ┆ Something     ┆               │
│        ┆         ┆        ┆           ┆   ┆            ┆         ┆ About Mary (… ┆               │
│ 1492   ┆ 348     ┆ 4      ┆ 974750340 ┆ … ┆ 12         ┆ 98102   ┆ Bullets Over  ┆ Comedy        │
│        ┆         ┆        ┆           ┆   ┆            ┆         ┆ Broadway      ┆               │
│        ┆         ┆        ┆           ┆   ┆            ┆         ┆ (1994)        ┆               │
│ 1492   ┆ 223     ┆ 5      ┆ 974750357 ┆ … ┆ 12         ┆ 98102   ┆ Clerks (1994) ┆ Comedy        │
│ 1492   ┆ 1449    ┆ 5      ┆ 974750357 ┆ … ┆ 12         ┆ 98102   ┆ Waiting for   ┆ Comedy        │
│        ┆         ┆        ┆           ┆   ┆            ┆         ┆ Guffman       ┆               │
│        ┆         ┆        ┆           ┆   ┆            ┆         ┆ (1996)        ┆               │
│ 1492   ┆ 3108    ┆ 5      ┆ 974750377 ┆ … ┆ 12         ┆ 98102   ┆ Fisher King,  ┆ Comedy|Drama| │
│        ┆         ┆        ┆           ┆   ┆            ┆         ┆ The (1991)    ┆ Romance       │
└────────┴─────────┴────────┴───────────┴───┴────────────┴─────────┴───────────────┴───────────────┘

In [4]:
test=pl.read_parquet(data_cfg["train"])
test.head()

shape: (5, 10)
┌────────┬─────────┬────────┬───────────┬───┬────────────┬─────────┬───────────────┬───────────────┐
│ userId ┆ movieId ┆ rating ┆ timestamp ┆ … ┆ occupation ┆ zipCode ┆ title         ┆ genres        │
│ ---    ┆ ---     ┆ ---    ┆ ---       ┆   ┆ ---        ┆ ---     ┆ ---           ┆ ---           │
│ i32    ┆ i32     ┆ i32    ┆ i64       ┆   ┆ i32        ┆ str     ┆ str           ┆ str           │
╞════════╪═════════╪════════╪═══════════╪═══╪════════════╪═════════╪═══════════════╪═══════════════╡
│ 1492   ┆ 1923    ┆ 4      ┆ 974750318 ┆ … ┆ 12         ┆ 98102   ┆ There's       ┆ Comedy        │
│        ┆         ┆        ┆           ┆   ┆            ┆         ┆ Something     ┆               │
│        ┆         ┆        ┆           ┆   ┆            ┆         ┆ About Mary (… ┆               │
│ 1492   ┆ 348     ┆ 4      ┆ 974750340 ┆ … ┆ 12         ┆ 98102   ┆ Bullets Over  ┆ Comedy        │
│        ┆         ┆        ┆           ┆   ┆            ┆         ┆ Broadway      ┆               │
│        ┆         ┆        ┆           ┆   ┆            ┆         ┆ (1994)        ┆               │
│ 1492   ┆ 223     ┆ 5      ┆ 974750357 ┆ … ┆ 12         ┆ 98102   ┆ Clerks (1994) ┆ Comedy        │
│ 1492   ┆ 1449    ┆ 5      ┆ 974750357 ┆ … ┆ 12         ┆ 98102   ┆ Waiting for   ┆ Comedy        │
│        ┆         ┆        ┆           ┆   ┆            ┆         ┆ Guffman       ┆               │
│        ┆         ┆        ┆           ┆   ┆            ┆         ┆ (1996)        ┆               │
│ 1492   ┆ 3108    ┆ 5      ┆ 974750377 ┆ … ┆ 12         ┆ 98102   ┆ Fisher King,  ┆ Comedy|Drama| │
│        ┆         ┆        ┆           ┆   ┆            ┆         ┆ The (1991)    ┆ Romance       │
└────────┴─────────┴────────┴───────────┴───┴────────────┴─────────┴───────────────┴───────────────┘

In [4]:
movies=pl.read_parquet(data_cfg["movies"])

In [5]:
movies.head()

shape: (5, 3)
┌─────────┬─────────────────────────────────┬──────────────────────────────┐
│ movieId ┆ title                           ┆ genres                       │
│ ---     ┆ ---                             ┆ ---                          │
│ i32     ┆ str                             ┆ str                          │
╞═════════╪═════════════════════════════════╪══════════════════════════════╡
│ 2       ┆ Jumanji (1995)                  ┆ Adventure|Children's|Fantasy │
│ 3       ┆ Grumpier Old Men (1995)         ┆ Comedy|Romance               │
│ 4       ┆ Waiting to Exhale (1995)        ┆ Comedy|Drama                 │
│ 5       ┆ Father of the Bride Part II (1… ┆ Comedy                       │
│ 6       ┆ Heat (1995)                     ┆ Action|Crime|Thriller        │
└─────────┴─────────────────────────────────┴──────────────────────────────┘

In [6]:
users=pl.read_parquet(data_cfg["users"])

In [7]:
users.head()

shape: (5, 5)
┌────────┬────────┬─────┬────────────┬─────────┐
│ userId ┆ gender ┆ age ┆ occupation ┆ zipCode │
│ ---    ┆ ---    ┆ --- ┆ ---        ┆ ---     │
│ i32    ┆ str    ┆ i32 ┆ i32        ┆ str     │
╞════════╪════════╪═════╪════════════╪═════════╡
│ 2      ┆ M      ┆ 56  ┆ 16         ┆ 70072   │
│ 3      ┆ M      ┆ 25  ┆ 15         ┆ 55117   │
│ 4      ┆ M      ┆ 45  ┆ 7          ┆ 02460   │
│ 5      ┆ M      ┆ 25  ┆ 20         ┆ 55455   │
│ 6      ┆ F      ┆ 50  ┆ 9          ┆ 55117   │
└────────┴────────┴─────┴────────────┴─────────┘

In [9]:
users.select(pl.col('age')).n_unique()

7

In [14]:
users.select(pl.col('occupation')).n_unique()

21

In [13]:
users.select(pl.col("occupation").value_counts())

shape: (21, 1)
┌────────────┐
│ occupation │
│ ---        │
│ struct[2]  │
╞════════════╡
│ {20,281}   │
│ {9,92}     │
│ {15,144}   │
│ {3,173}    │
│ {5,112}    │
│ …          │
│ {4,759}    │
│ {2,267}    │
│ {18,70}    │
│ {14,302}   │
│ {6,236}    │
└────────────┘

In [11]:
users.select(pl.col('zipCode')).n_unique()

3439