In [27]:
import gc
import logging
import math
import random
import time
import warnings
from datetime import datetime
from operator import itemgetter
from pathlib import Path

logger=logging.getLogger(__name__)
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
from collections import defaultdict

from tqdm import tqdm
import pickle

In [13]:
def reduce_mem(df):
    starttime=time.time()
    numerics=['int16','int32','int64','float16','float32','float64']
    start_mem=df.memory_usage().sum()/1024**2
    for col in df.columns:
        if col in numerics:
            c_min=df[col].min()
            c_max=df[col].max()
            if pd.isnull(c_min) or pd.isnull(c_max):
                continue
            if str(df[col].types)[:3]=='int':
                if c_min>np.iinfo(np.int8).min and c_max<np.iinfo(np.int8).max:
                    df[col]=df[col].astype(np.int8)
                elif c_min>np.iinfo(np.int16).min and c_max<np.iinfo(np.int16).max:
                    df[col]=df[col].astype(np.int16)
                elif c_min>np.iinfo[np.int32].min and c_max<np.iinfo(np.int32).max:
                    df[col]=df[col].astype(np.int32)
            else:
                if c_min>np.iinfo(np.float16).min and c_max<np.iinfo(np.float16).max:
                    df[col]=df[col].astype(np.float16)
                elif c_min>np.iinfo(np.float32).min and c_max<np.iinfo(np.float32).max:
                    df[col]=df[col].astype(np.float32)
    end_mem=df.memory_usage().sum()/1024**2
    print(f'--Memory usage after optimization: {end_mem:.2f} MB, about {(start_mem-end_mem)/starttime*100}%, time spend {(time.time()-starttime)/60} min')

In [16]:
def get_all_click_sample(sample_nums=10000):
    """
    训练集中采样一部分数据调试
    :param sample_nums:
    :return:
    """
    all_click=pd.read_csv('./data/train_click_log.csv')
    all_user_ids=all_click.user_id.unique()

    sample_user_ids=np.random.choice(all_user_ids,size=sample_nums,replace=False)
    all_click=all_click[all_click['user_id'].isin(sample_user_ids)]

    # 按照多列去重，('user_id','click_article_id','click_timestamp')都一样才视为相同
    all_click=all_click.drop_duplicates(['user_id','click_article_id','click_timestamp'])
    return all_click

def get_all_click_df(offline):
    if offline:
        all_click=pd.read_csv('./data/train_click_log.csv')[:20000]
    else:
        all_click=pd.concat([pd.read_csv('./data/train_click_log.csv')[:10000],pd.read_csv('./data/testA_click_log.csv')[:10000]])
    return all_click

In [30]:
all_click_df=get_all_click_df(offline=False)
all_click_df.head()

,user_id,click_article_id,click_timestamp,click_environment,click_deviceGroup,click_os,click_country,click_region,click_referrer_type
0,199999,160417,1507029570190,4,1,17,1,13,1
1,199999,5408,1507029571478,4,1,17,1,13,1
2,199999,50823,1507029601478,4,1,17,1,13,1
3,199998,157770,1507029532200,4,1,17,1,25,5
4,199998,96613,1507029671831,4,1,17,1,25,5

In [31]:
def get_user_item_time(click_df):
    '''获取用户-文章-点击时间字典 {user1:{item1:time1,item2:time2}}'''
    memo={}
    for user_id,group in click_df.groupby('user_id'):
        group_sorted=group.sort_values('click_timestamp')
        item_time_dict=dict(zip(group['click_article_id'],group['click_timestamp']))
        memo[user_id]=item_time_dict
    return memo

In [32]:
def get_item_topk_click(click_df,k):
    '''获取点击最多的前k个文章'''
    return click_df['click_article_id'].value_counts().index[:k]

In [37]:
tmp=get_user_item_time(all_click_df)
tmp

{196381: {233917: 1507036600306},
 196382: {5408: 1507036793030, 206661: 1507036823030},
 196383: {50823: 1507039157875, 206934: 1507039187875},
 196384: {156624: 1507036261249, 158536: 1507036291249},
 196385: {64329: 1507036351078, 156560: 1507036381078},
 196386: {62599: 1507036220261, 195843: 1507036250261},
 196387: {156624: 1507036223016, 158536: 1507036253016},
 196388: {214800: 1507119006577, 58606: 1507119036577},
 196389: {156560: 1507041936443,
  308156: 1507043103354,
  123365: 1507043203520,
  286161: 1507043233520},
 196390: {336476: 1507036542066, 272143: 1507036572066},
 196391: {64329: 1507036349694, 272143: 1507036402548, 199198: 1507036432548},
 196392: {286161: 1507036285554, 300074: 1507037854664, 300470: 1507037884664},
 196393: {286161: 1507039185835, 283041: 1507039215835},
 196394: {182513: 1507039011330, 129029: 1507039041330},
 196395: {236726: 1507036551897, 157332: 1507036581897},
 196396: {233717: 1507115265310, 293301: 1507136606607, 123909: 1507136636607},
 196397: {156624: 1507038978656, 160417: 1507039008656},
 196398: {272143: 1507036308301, 199198: 1507036338301},
 196399: {161409: 1507036318448, 272143: 1507036348448},
 196400: {233917: 1507036198439, 182513: 1507036228439},
 196401: {156624: 1507036266490, 162765: 1507036296490},
 196402: {199197: 1507038525354, 83799: 1507038814758, 84862: 1507038844758},
 196403: {156624: 1507036191817, 284474: 1507036221817},
 196404: {236961: 1507036354316, 156447: 1507036384316},
 196405: {272143: 1507036486631,
  199198: 1507036620461,
  175040: 1507036695695,
  324823: 1507036725695},
 196406: {236961: 1507036254494, 234991: 1507036928477, 156624: 1507036958477},
 196407: {64329: 1507036460235, 199198: 1507036483227, 156560: 1507036513227},
 196408: {336476: 1507036567020, 272143: 1507036807954, 225055: 1507036837954},
 196409: {156560: 1507036179406, 64329: 1507036209406},
 196410: {157332: 1507036179658, 208077: 1507036209658},
 196411: {156619: 1507061175233, 162655: 1507061205233},
 196412: {199198: 1507037790895, 341838: 1507037820895},
 196413: {15166: 1507036179027, 17330: 1507036209027},
 196414: {156624: 1507036276592, 158229: 1507036306592},
 196415: {336476: 1507036285081, 272143: 1507036315081},
 196416: {63657: 1507044730237, 63685: 1507044760237},
 196417: {167792: 1507036165937, 358512: 1507036195937},
 196418: {160417: 1507036190482, 156624: 1507036220482},
 196419: {156560: 1507036201432,
  50823: 1507036223762,
  236726: 1507036272292,
  161409: 1507036283851,
  224171: 1507036294041,
  65373: 1507036324041},
 196420: {156624: 1507036274962,
  160417: 1507036277313,
  158536: 1507036362653,
  156560: 1507036539669,
  156447: 1507036569669},
 196421: {161409: 1507036180987, 336476: 1507036210987},
 196422: {136791: 1507036157558, 136770: 1507036187558},
 196423: {156624: 1507036174582,
  162655: 1507036217298,
  158536: 1507036366711,
  272143: 1507036396711},
 196424: {50823: 1507037793329, 156624: 1507037823329},
 196425: {156624: 1507036269689,
  160417: 1507036275575,
  156447: 1507036595593,
  156560: 1507038413201,
  50823: 1507039212817,
  355866: 1507040723130,
  39857: 1507040753130},
 196426: {182513: 1507036247093, 336476: 1507036330753, 284474: 1507036360753},
 196427: {84422: 1507036160861, 84916: 1507036749676, 83622: 1507036779676},
 196428: {157332: 1507036168777, 166430: 1507036198777},
 196429: {272143: 1507036205065, 303819: 1507036676376, 226569: 1507036706376},
 196430: {199198: 1507037453354, 235440: 1507037483354},
 196431: {156624: 1507040746603, 272143: 1507040776603},
 196432: {156624: 1507036257588,
  272143: 1507037858113,
  16129: 1507038483721,
  362950: 1507038485330,
  96812: 1507042267138,
  198659: 1507042297138},
 196433: {96152: 1507036232167, 70033: 1507036262167},
 196434: {156624: 1507037021796, 158536: 1507037063436, 156560: 1507037093436},
 196435: {348111: 1507037183516, 114743: 1507037213516},
 196436: {156560: 1507043638403, 284547: 1507043668403},
 196437: {336476: 1507037276054, 162655: 1507037306054},
 196438: {284547: 1507050352042, 129029: 1507050382042},
 196439: {272143: 1507036249887, 175040: 1507036279887},
 196440: {98399: 1507036424437, 98332: 1507036454437},
 196441: {156624: 1507036635148, 348111: 1507036665148},
 196442: {208322: 1507046749778, 284547: 1507046779778},
 196443: {156624: 1507036115317, 158082: 1507036311219, 162765: 1507036341219},
 196444: {156624: 1507036156627, 233917: 1507036186627},
 196445: {199198: 1507036915347,
  272143: 1507037008315,
  16129: 1507037937857,
  162765: 1507037967857},
 196446: {336476: 1507036316560, 348111: 1507036346560},
 196447: {156560: 1507039053350, 336476: 1507039083350},
 196448: {161409: 1507036139535,
  161584: 1507036289115,
  199197: 1507036783476,
  50823: 1507036956590,
  50383: 1507037245121,
  50815: 1507037275121},
 196449: {64329: 1507036585566, 272143: 1507036635951, 156560: 1507036665951},
 196450: {336476: 1507036141287, 161409: 1507036171287},
 196451: {162655: 1507036430228, 160417: 1507036460228},
 196452: {64329: 1507038660477, 272143: 1507038690477},
 196453: {206168: 1507041844095,
  285298: 1507042778547,
  199197: 1507043732775,
  187065: 1507043958078,
  245045: 1507043988078},
 196454: {175040: 1507036319232,
  199198: 1507036321906,
  272143: 1507036385177,
  272761: 1507036415177},
 196455: {233917: 1507036163399, 71500: 1507036193399},
 196456: {352092: 1507036131330, 288841: 1507036161330},
 196457: {348111: 1507036185959,
  156560: 1507036658987,
  50823: 1507036859417,
  5408: 1507036889417},
 196458: {157332: 1507036134397, 71500: 1507036164397},
 196459: {160417: 1507036081541, 157332: 1507036111541},
 196460: {336476: 1507038219235,
  348111: 1507038971967,
  64329: 1507039338257,
  175040: 1507039394302,
  199197: 1507039424302},
 196461: {70033: 1507038048281, 156624: 1507038078281},
 196462: {285030: 1507036072898, 2179: 1507036102898},
 196463: {285298: 1507036871262, 272143: 1507036901262},
 196464: {160417: 1507036092282, 162655: 1507036111647, 272143: 1507036141647},
 196465: {348111: 1507036525049,
  199198: 1507036664714,
  156624: 1507036780806,
  160974: 1507036810806},
 196466: {308166: 1507036101463, 307856: 1507036485292, 307415: 1507036515292},
 196467: {199198: 1507037044071, 64329: 1507037074071},
 196468: {156624: 1507036052499, 156560: 1507036082499},
 196469: {160417: 1507036128039, 272143: 1507036855973, 157332: 1507036885973},
 196470: {199198: 1507036458298, 272143: 1507036488298},
 196471: {156624: 1507036037877, 199197: 1507036067877},
 196472: {289249: 1507036128711, 114743: 1507036961038, 114795: 1507036991038},
 196473: {336476: 1507036855859, 272143: 1507036885859},
 196474: {64329: 1507036746589, 272143: 1507036776589},
 196475: {336476: 1507036501465, 284474: 1507036531465},
 196476: {206168: 1507043616391,
  272143: 1507044185933,
  199198: 1507044320367,
  224658: 1507044464426,
  198659: 1507044494426},
 196477: {156624: 1507036031342, 156447: 1507036061342},
 196478: {50823: 1507036040850, 233917: 1507036070850},
 196479: {158229: 1507037084803, 158082: 1507037114803},
 196480: {64329: 1507041748130, 272143: 1507041778130},
 196481: {336476: 1507036612408, 284474: 1507036863629, 285255: 1507036893629},
 196482: {78374: 1507037755281, 59829: 1507037785281},
 196483: {156560: 1507036068825, 285298: 1507036098825},
 196484: {156560: 1507042316414, 206168: 1507042346414},
 196485: {285648: 1507035990508, 285343: 1507036020508},
 196486: {162338: 1507040286219, 159084: 1507040289193, 159847: 1507040319193},
 196487: {199198: 1507036174439,
  272143: 1507036263197,
  162655: 1507036276504,
  198659: 1507036306504},
 196488: {175040: 1507035989352, 161409: 1507036019352},
 196489: {286161: 1507036601838, 331226: 1507037595593, 272143: 1507037625593},
 196490: {156447: 1507036028311, 136075: 1507036058311},
 196491: {64329: 1507036182873, 160417: 1507036212873},
 196492: {175040: 1507036225496, 199198: 1507036255496},
 196493: {160417: 1507036128281, 162655: 1507036158281},
 196494: {284474: 1507035963754, 118683: 1507035993754},
 196495: {161409: 1507039418870, 199197: 1507039448870},
 196496: {156560: 1507037015516,
  160148: 1507037156681,
  160417: 1507037164584,
  64329: 1507037182481,
  162765: 1507037219283,
  158082: 1507037524601,
  160974: 1507037554601},
 196497: {199197: 1507041783748, 206934: 1507041813748},
 196498: {182513: 1507036037831, 199198: 1507036067831},
 196499: {156447: 1507035973846, 136075: 1507036003846},
 196500: {285342: 1507065278376, 338350: 1507065308376},
 196501: {156624: 1507036092881, 158536: 1507036256826, 272143: 1507036286826},
 196502: {175040: 1507036373137, 272143: 1507036374880, 199198: 1507036404880},
 196503: {64329: 1507036333105,
  162655: 1507036775043,
  3241: 1507037480091,
  324823: 1507037699637,
  4967: 1507037872384,
  121350: 1507038076579,
  272143: 1507038160149,
  198659: 1507038226363,
  156560: 1507038256363},
 196504: {181928: 1507036267088, 181873: 1507036297088},
 196505: {156560: 1507037215954, 284474: 1507037245954},
 196506: {160974: 1507036036296,
  234832: 1507037315883,
  65373: 1507037738472,
  162655: 1507037768472},
 196507: {182513: 1507038115617, 175040: 1507038902233, 272143: 1507038932233},
 196508: {199198: 1507036539820, 198659: 1507036694497, 13811: 1507036724497},
 196509: {352092: 1507036006522,
  272143: 1507036232694,
  264825: 1507036484326,
  156560: 1507036514326},
 196510: {199198: 1507037816825,
  182472: 1507038007419,
  121834: 1507038046786,
  261612: 1507038076786},
 196511: {348111: 1507036199952, 156560: 1507036229952},
 196512: {156560: 1507036878976, 272143: 1507036908976},
 196513: {272143: 1507036373822,
  254489: 1507036387614,
  198659: 1507036389793,
  255207: 1507036400129,
  324823: 1507036400781,
  336476: 1507036787250,
  140324: 1507036817250},
 196514: {71500: 1507036106670, 300074: 1507036136670},
 196515: {199198: 1507036659853, 272143: 1507037019865, 286161: 1507037049865},
 196516: {199198: 1507036153047, 225055: 1507036209684, 107226: 1507036239684},
 196517: {272143: 1507035994036,
  324823: 1507036117630,
  156624: 1507036354471,
  352092: 1507036450654,
  70036: 1507036480654},
 196518: {285298: 1507045169814, 199197: 1507045254251, 187065: 1507045284251},
 196519: {224171: 1507036676569,
  166445: 1507050269982,
  199197: 1507050963893,
  96152: 1507050993893},
 196520: {348111: 1507036006179,
  348129: 1507036475230,
  348086: 1507036494226,
  348080: 1507036528768,
  348099: 1507036558768},
 196521: {156624: 1507035929445,
  160417: 1507035933642,
  234832: 1507036016191,
  158082: 1507036046191},
 196522: {233671: 1507035915240, 272294: 1507035945240},
 196523: {166430: 1507036125732,
  233917: 1507038325929,
  236961: 1507038377238,
  235715: 1507038407238},
 196524: {285343: 1507036025776, 286161: 1507036055776},
 196525: {156624: 1507035943360, 162765: 1507035973360},
 196526: {233917: 1507035924070, 118464: 1507035954070},
 196527: {166430: 1507036806655, 156560: 1507036836655},
 196528: {156624: 1507035983547,
  156560: 1507037099138,
  162300: 1507037369212,
  162655: 1507037513203,
  286161: 1507037790544,
  182394: 1507037820544},
 196529: {162655: 1507037098541, 156560: 1507037128541},
 196530: {160417: 1507035918654, 286161: 1507035948654},
 196531: {352116: 1507035904822, 272143: 1507035934822},
 196532: {348111: 1507035972922, 272143: 1507036002922},
 196533: {199198: 1507036606853,
  182394: 1507036811591,
  198659: 1507036960237,
  118753: 1507037192368,
  156560: 1507037222368},
 196534: {286161: 1507038507704,
  331424: 1507039899779,
  348111: 1507040111751,
  162655: 1507040444701,
  64329: 1507041123401,
  135899: 1507041153401},
 196535: {16132: 1507035890523, 14102: 1507037053838, 16609: 1507037083838},
 196536: {227557: 1507035943222, 227555: 1507035973222},
 196537: {235230: 1507063312675, 338350: 1507063342675},
 196538: {156560: 1507035973664, 166430: 1507036003664},
 196539: {286161: 1507036070529, 83646: 1507036100529},
 196540: {348111: 1507039721266, 199197: 1507039751266},
 196541: {285648: 1507035871495, 300470: 1507035901495},
 196542: {236726: 1507038332227, 156624: 1507038411450, 162765: 1507038441450},
 196543: {199198: 1507036065027, 272143: 1507036095027},
 196544: {156624: 1507038227773, 284474: 1507038257773},
 196545: {351411: 1507035935758, 352092: 1507035965758},
 196546: {181928: 1507035884310, 160417: 1507035914310},
 196547: {156624: 1507036012215, 161409: 1507036104898, 272143: 1507036134898},
 196548: {256132: 1507035865218, 2907: 1507035895218},
 196549: {254388: 1507035959451,
  255231: 1507036043678,
  255959: 1507037315304,
  255207: 1507037345304},
 196550: {199198: 1507036129231, 182513: 1507036159231},
 196551: {160417: 1507035862898, 272143: 1507035892898},
 196552: {338350: 1507035883190, 337946: 1507035915436, 272143: 1507035945436},
 196553: {199198: 1507036344110, 175040: 1507036374110},
 196554: {285298: 1507036108760, 234832: 1507036455750, 162655: 1507036485750},
 196555: {199197: 1507051765853, 218098: 1507051795853},
 196556: {336476: 1507035988563, 199198: 1507036018563},
 196557: {161409: 1507039364573, 161584: 1507039394573},
 196558: {272143: 1507036296744, 162655: 1507036326744},
 196559: {199197: 1507039874124,
  362950: 1507039921617,
  336476: 1507040302169,
  129029: 1507040332169},
 196560: {272143: 1507038647285, 64329: 1507038677285},
 196561: {161409: 1507035988644, 233917: 1507036018644},
 196562: {156619: 1507055997093, 156560: 1507057094702, 199197: 1507057124702},
 196563: {336476: 1507035967197,
  175040: 1507039524329,
  64329: 1507039603119,
  272143: 1507039633119},
 196564: {303292: 1507035896428, 108854: 1507035926428},
 196565: {199198: 1507036232835, 156624: 1507036262835},
 196566: {183884: 1507035855206, 215853: 1507035885206},
 196567: {74778: 1507036241025, 96077: 1507036271025},
 196568: {337266: 1507035895896,
  300128: 1507035959937,
  272143: 1507036038711,
  297887: 1507036046817,
  298310: 1507036104804,
  298380: 1507037030774,
  298646: 1507037060774},
 196569: {157332: 1507035861343, 285298: 1507035891343},
 196570: {272143: 1507036272757, 64329: 1507036276180, 199198: 1507036306180},
 196571: {199198: 1507036190734, 182394: 1507036295900, 96077: 1507036325900},
 196572: {160417: 1507036386332, 162655: 1507036416332},
 196573: {50823: 1507035951183, 50864: 1507035981183},
 196574: {160417: 1507035871943, 156560: 1507035901943},
 196575: {199198: 1507036073322, 272143: 1507036189707, 198659: 1507036219707},
 196576: {156624: 1507045391831, 199197: 1507045421831},
 196577: {156560: 1507037704204, 336476: 1507037734204},
 196578: {156624: 1507036629081, 300074: 1507037141979, 297887: 1507037171979},
 196579: {157332: 1507035837111,
  166430: 1507036066508,
  84422: 1507036119892,
  79376: 1507036149892},
 196580: {29840: 1507037559383, 313434: 1507037618390, 159847: 1507037648390},
 196581: {64329: 1507036069006, 272143: 1507036249102, 199198: 1507036279102},
 196582: {272143: 1507036012691, 199198: 1507036042691},
 196583: {70033: 1507038159848, 161409: 1507038189848},
 196584: {156624: 1507035821906, 158229: 1507035851906},
 196585: {360990: 1507035812588, 58434: 1507035842588},
 196586: {50823: 1507035945201, 64329: 1507035975201},
 196587: {158229: 1507035824570, 156560: 1507036531054, 157332: 1507036561054},
 196588: {161409: 1507035853925, 50823: 1507035883925},
 196589: {336476: 1507036274805, 199198: 1507036304805},
 196590: {272143: 1507036044482,
  59499: 1507036546828,
  199198: 1507038281027,
  198659: 1507038311027},
 196591: {348111: 1507036752932, 272143: 1507037931524, 199198: 1507037961524},
 196592: {348111: 1507035928892, 272143: 1507036439001, 199198: 1507036469001},
 196593: {32578: 1507035816143, 25370: 1507036039678, 160474: 1507036069678},
 196594: {156624: 1507035895663,
  348111: 1507036760846,
  272143: 1507036870476,
  156560: 1507036900476},
 196595: {336476: 1507035853115, 198659: 1507036071839, 13811: 1507036101839},
 196596: {182513: 1507036266169, 336476: 1507036296169},
 196597: {157332: 1507036136573, 65373: 1507036166573},
 196598: {83646: 1507035970582, 83799: 1507036000582},
 196599: {156624: 1507035812447, 157332: 1507035842447},
 196600: {284474: 1507035875122, 59829: 1507035905122},
 196601: {336476: 1507036162837, 286161: 1507036192837},
 196602: {199198: 1507035918876, 272143: 1507035948876},
 196603: {16132: 1507035823495, 16609: 1507036138769, 289630: 1507036168769},
 196604: {157332: 1507036307493, 156560: 1507036337493},
 196605: {160974: 1507035785982, 160417: 1507035815982},
 196606: {156560: 1507037042879, 272143: 1507037452712, 166430: 1507037482712},
 196607: {156624: 1507035772941, 195839: 1507035797035, 166228: 1507035827035},
 196608: {162655: 1507035824191, 68398: 1507035854191},
 196609: {272143: 1507036360968, 64329: 1507036390968},
 196610: {166534: 1507056246711,
  199197: 1507056376128,
  272143: 1507056523914,
  198659: 1507056589814,
  300473: 1507056704389,
  324823: 1507056823852,
  284547: 1507059107058,
  286161: 1507059241100,
  285342: 1507059410788,
  187065: 1507059559910,
  96999: 1507059589910},
 196611: {156560: 1507036878253, 336476: 1507036908253},
 196612: {337876: 1507035743772,
  225364: 1507035876779,
  311548: 1507036744489,
  67641: 1507036774489},
 196613: {175040: 1507035856998, 64329: 1507035919173, 272143: 1507035949173},
 196614: {182513: 1507036390437, 233917: 1507036437217, 336476: 1507036467217},
 196615: {245784: 1507036020598, 245099: 1507036050598},
 196616: {44563: 1507035785799, 175325: 1507035815799},
 196617: {199198: 1507038353656, 61611: 1507038383656},
 196618: {199198: 1507036556841,
  272143: 1507038350816,
  198659: 1507038364276,
  182394: 1507038378338,
  156560: 1507038408338},
 196619: {348111: 1507036030516,
  162655: 1507036202059,
  33333: 1507036559035,
  233917: 1507037189304,
  182513: 1507037219304},
 196620: {182513: 1507037474637,
  336476: 1507038488426,
  199197: 1507040930970,
  160417: 1507041196237,
  272143: 1507041226237},
 196621: {272143: 1507036071466, 156560: 1507041321853, 199197: 1507041351853},
 196622: {161409: 1507036211796, 161584: 1507036241796},
 196623: {50823: 1507035787788, 50383: 1507035817788},
 196624: {199198: 1507039385167, 272143: 1507039506509, 175040: 1507039536509},
 196625: {303292: 1507037009114, 303819: 1507037039114},
 196626: {272143: 1507035979443, 199198: 1507036009443},
 196627: {78374: 1507036513409, 272143: 1507036620236, 198659: 1507036650236},
 196628: {199198: 1507035971915, 272143: 1507036001915},
 196629: {199198: 1507036045658, 198659: 1507036125030, 218144: 1507036155030},
 196630: {156624: 1507046701319, 284547: 1507046731319},
 196631: {64329: 1507035921729, 175040: 1507035951729},
 196632: {157332: 1507035761232, 50823: 1507035791232},
 196633: {348111: 1507040279143, 156560: 1507040309143},
 196634: {156560: 1507035830117, 96077: 1507036104914, 59829: 1507036134914},
 196635: {156624: 1507035721941, 157332: 1507036565836, 161409: 1507036595836},
 196636: {272143: 1507043649680,
  199197: 1507046441023,
  336476: 1507046551642,
  284547: 1507048417993,
  286161: 1507048555275,
  129029: 1507048585275},
 196637: {348111: 1507035748091, 156560: 1507051126640, 284547: 1507051156640},
 196638: {50823: 1507035727282, 233917: 1507035757282},
 196639: {336476: 1507036049567, 284474: 1507036214537, 199198: 1507036244537},
 196640: {235230: 1507050639763, 199197: 1507050669763},
 196641: {157332: 1507035695322, 286161: 1507035725322},
 196642: {156624: 1507037039225, 156560: 1507037069225},
 196643: {284474: 1507037856734,
  156624: 1507039031276,
  156560: 1507039120111,
  285298: 1507039150111},
 196644: {298224: 1507036388273, 57607: 1507036418273},
 196645: {182513: 1507036087529,
  336476: 1507036160824,
  284474: 1507036266147,
  348111: 1507036282902,
  156560: 1507038362283,
  50823: 1507038438434,
  199197: 1507038637220,
  272143: 1507038664975,
  332220: 1507040425378,
  331424: 1507040491293,
  332353: 1507040709154,
  331818: 1507040832434,
  332297: 1507040874988,

In [41]:
def itemcf_sim(df):
    '''计算物品的相似度矩阵'''
    user_item_time_dict =get_user_item_time(df)
    # i2i_sim[i][j]统计i和j共有的受众个数
    i2i_sim=defaultdict(dict)
    # 统计每个物品受众个数
    item_cnt=defaultdict(int)
    for user,item_time_list in tqdm(user_item_time_dict.items()):
        for i,i_click_time in item_time_list.items():
            # 更新
            item_cnt[i]+=1
            for j, j_click_time in item_time_list.items():
                if i!=j:
                    i2i_sim[i].setdefault(j,0)
                    # 加权弱化：用户点击的物品越多，对每对物品的贡献就越小
                    i2i_sim[i][j]+=1/math.log(len(item_time_list)+1)
    i2i_sim_=i2i_sim.copy()

    for i, related_items in i2i_sim.items():
        for j, wij in related_items.items():
            i2i_sim_[i][j]=wij/math.sqrt(item_cnt[i]*item_cnt[j])
    # 保存相似度矩阵
    pickle.dump(i2i_sim_, open('./save/itemcf_i2i_sim.pkl', 'wb'))
i2i_sim=itemcf_sim(all_click_df)

100%|██████████| 7721/7721 [00:00<00:00, 108428.46it/s]

In [51]:
def item_based_rec(user_id,user_item_time_dict,i2i_sim,sim_item_topk,recall_item_num,item_topk_click):
    """
    基于物品的协同过滤
    :param user_id: 用户Id
    :param user_item_time_dict: {user1: {item1: time1, item2: time2..}...}
    :param i2i_sim:相似性矩阵
    :param sim_item_topk: 前k个
    :param recall_item_num:要求召回的文章数量
    :param item_topk_click:点击次数最多的文章列表，用于召回补齐
    :return: {item1:score1, item2: score2...}
    """
    # 用户点击过的物品
    user_hist_items=user_item_time_dict[user_id]

    item_rank={}
    for i,click_time in user_hist_items.items():
        # 为点击过的物品找到最相似的sim_item_topk
        for j ,wij in sorted(i2i_sim[i].items(),key=lambda x:x[1],reverse=True)[:sim_item_topk]:
            # 去重
            if j not in user_hist_items:
                item_rank.setdefault(j,0)
                item_rank[j]+=wij
    # 如果结果不满足召回数量，则用热门物品补齐
    if len(item_rank)<recall_item_num:
        for i,item in enumerate(item_topk_click):
            if item not in item_rank:
                item_rank[item]=i-100
                if len(item_rank)==recall_item_num:break
    # 保留得分最高的
    item_rank=sorted(item_rank.items(),key=lambda x:x[1],reverse=True)[:recall_item_num]
    return item_rank

In [52]:
user_recall_items_dict=defaultdict(dict)
user_item_time_dict=get_user_item_time(all_click_df)

# 物品相似度矩阵
i2i_sim=pickle.load(open('./save/itemcf_i2i_sim.pkl','rb'))

# 相似文章数量
sim_item_topk=10
# 找回个数
recall_item_num=10
# 热门物品个数
item_topk_click=get_item_topk_click(all_click_df,k=50)

# 为每个用户推荐
for user in tqdm(all_click_df['user_id'].unique()):
    user_recall_items_dict[user]=item_based_rec(user,user_item_time_dict,i2i_sim,sim_item_topk,recall_item_num,item_topk_click)

 14%|█▍        | 1083/7721 [00:00<00:01, 5230.04it/s]

[(107301, 0.1786889993417549), (50864, 0.15074178380379075), (160974, 0.14414482050765215), (50383, 0.13514557010693226), (158536, 0.11041310336685785), (161160, 0.10840791429656242), (207469, 0.09464216817386983), (162655, 0.0938444249093069), (156624, 0.08042054203791298), (50619, 0.07762341432436974)]
[(119044, 0.1600208841973003), (273394, 0.1600208841973003), (206159, 0.1600208841973003), (69433, 0.1600208841973003), (206606, 0.1600208841973003), (161227, 0.1600208841973003), (161363, 0.1600208841973003), (225463, 0.022050351725411414), (300470, 0.01476025681000086), (160974, 0.008794040961419797)]
[(225499, 0.25365892483943775), (292708, 0.15610473950771406), (70673, 0.12371007915228557), (237055, 0.12371007915228557), (225514, 0.11038271988126416), (342917, 0.11038271988126416), (166430, 0.07913401120276446), (224857, 0.071424047500042), (330745, 0.06896974169838807), (166445, 0.06152132588197724)]
[(160974, 0.24817664391348115), (31267, 0.1316994362492872), (97661, 0.11343971980809854), (100954, 0.11343971980809854), (225463, 0.1091240539728442), (96288, 0.09382457146014178), (32714, 0.09312556445031639), (202557, 0.08687465921548786), (300470, 0.08257752929398565), (96812, 0.07949171330613487)]
[(285808, 0.3594064321540561), (182513, 0.24996876218991318), (145329, 0.19278823416444013), (285648, 0.18481089989236407), (195586, 0.17201904480216956), (285638, 0.1367782296577098), (207731, 0.12524482954591737), (348111, 0.11639602986490896), (233917, 0.1148109975134215), (336607, 0.11134994710096138)]
[(158192, 0.1442231472937707), (84371, 0.13536170965002617), (58193, 0.12745898607466183), (199197, 0.11110277035639192), (313431, 0.10698475713146899), (83565, 0.1028050527895362), (235827, 0.10113769184742637), (70646, 0.08409954033602747), (206934, 0.08146138019435344), (190559, 0.0801497244938313)]
[(175040, 0.2415397583322196), (199198, 0.2205925817690975), (272143, 0.19735844511100942), (207469, 0.09464216817386983), (205861, 0.09016844005556021), (50823, 0.07718967948100029), (156560, 0.07545421476168913), (207979, 0.07222871901160036), (167172, 0.07222871901160036), (336476, 0.07029233252016003)]
[(199198, 0.33362887301109817), (336476, 0.2101813750101867), (64329, 0.19735844511100942), (198659, 0.16417387594471664), (284474, 0.15144831824412505), (175040, 0.14832189638870905), (31267, 0.1316994362492872), (182513, 0.12241980393274354), (97661, 0.11343971980809854), (100954, 0.11343971980809854)]
[(160974, 0.3974549317972365), (156560, 0.2842665177770215), (157332, 0.20758340271185255), (162655, 0.1835217364329242), (162765, 0.1813363905861373), (166283, 0.15950322319103769), (162300, 0.1339870574474143), (158082, 0.13299105591176386), (300470, 0.11461550433944184), (158229, 0.11101658048608612)]
[(297970, 0.43935014561520125), (199198, 0.4355792283392735), (64329, 0.19735844511100942), (156560, 0.16277583453331607), (324823, 0.14920713485641457), (175040, 0.14832189638870905), (13811, 0.11211930324396888), (140324, 0.10355582242660198), (336476, 0.09378534514527773), (156624, 0.08526492529654099)]
[(272143, 0.3660697727370525), (156560, 0.2718817989007004), (175040, 0.2415397583322196), (199198, 0.2205925817690975), (111031, 0.20979811974466375), (158536, 0.1832251919447172), (162765, 0.1813363905861373), (157332, 0.15690440665465014), (156447, 0.15526760277709728), (336476, 0.1474306215878425)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (158536, 0.23190308108539537), (160417, 0.22456536254556514), (162300, 0.21585021382334774), (162765, 0.1813363905861373), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (156560, 0.1369881430866801), (59758, 0.12538033733281437)]
[(199198, 0.49483930091243444), (175040, 0.4724337197539763), (182513, 0.24996876218991318), (348111, 0.2483009213323994), (156624, 0.21204126259044198), (198659, 0.20908998133756568), (156560, 0.17969307321424893), (284474, 0.16145238513086735), (233917, 0.1148109975134215), (341838, 0.10715630398092232)]
[(199198, 0.2742467191433369), (64329, 0.19735844511100942), (107301, 0.1786889993417549), (198659, 0.16417387594471664), (175040, 0.14832189638870905), (156560, 0.1042388584525598), (207469, 0.09464216817386983), (336476, 0.09378534514527773), (156624, 0.08526492529654099), (324823, 0.08504076711209806)]
[(336476, 0.20550546036295064), (348111, 0.1448565856131705), (234000, 0.08238105303863753), (118464, 0.07805236975385703), (235363, 0.07805236975385703), (242643, 0.07805236975385703), (275192, 0.07775616900834297), (232753, 0.07585326888556977), (278808, 0.07585326888556977), (279159, 0.07585326888556977)]
[(199198, 0.2742467191433369), (64329, 0.19735844511100942), (198659, 0.16417387594471664), (175040, 0.14832189638870905), (169156, 0.11789636534962156), (66206, 0.10441160008718423), (50626, 0.10441160008718423), (156560, 0.1042388584525598), (336476, 0.09378534514527773), (65753, 0.09367120004034671)]
[(160974, 0.17650918576607283), (160417, 0.164480749891623), (158536, 0.15203204245306504), (156560, 0.06263948773013987), (161858, 0.061212749824087684), (300470, 0.05569242547034934), (162300, 0.05280282222593651), (272143, 0.052215875368756395), (236802, 0.05100697232983947), (210994, 0.05100697232983947)]
[(156560, 0.22482707672469027), (162765, 0.1813363905861373), (76454, 0.17002324109946493), (157332, 0.14044105998906584), (160417, 0.13229798097224488), (158229, 0.11101658048608612), (78369, 0.10355582242660198), (107039, 0.0972614455180946), (167259, 0.0872336478212462), (272143, 0.08526492529654099)]
[(157730, 0.6436363296498353), (175040, 0.5743901967282454), (67542, 0.45511961331341866), (160974, 0.4308817068796773), (300470, 0.36270099437894693), (297941, 0.32181816482491765), (111809, 0.32181816482491765), (182394, 0.30611831351675295), (156560, 0.3008695370251451), (336476, 0.2189264704903674)]
[(272143, 0.3680320642886147), (182513, 0.30720340308950495), (64329, 0.2908849142892575), (175040, 0.2671006070403644), (348111, 0.1757781837326702), (198659, 0.16133250919593656), (233917, 0.1148109975134215), (182394, 0.11014153830293937), (341838, 0.10715630398092232), (284474, 0.09069446284952913)]
[(272143, 0.4185620056825601), (64329, 0.2205925817690975), (175040, 0.1845285420073168), (182513, 0.17965444483233534), (336476, 0.17124482268983862), (198659, 0.16133250919593656), (299767, 0.1289882580222607), (182394, 0.11014153830293937), (96481, 0.09112645567325996), (284474, 0.08069039596278683)]
[(31267, 0.1316994362492872), (182513, 0.12241980393274354), (336476, 0.11639602986490896), (97661, 0.11343971980809854), (100954, 0.11343971980809854), (96288, 0.09382457146014178), (32714, 0.09312556445031639), (272143, 0.08139769494087935), (284474, 0.08069039596278683), (178365, 0.07603670497064792)]
[(336476, 0.3325408272229608), (64329, 0.31699397309390875), (272143, 0.25256075484126883), (199198, 0.2417631829069086), (156624, 0.1975698978069605), (348111, 0.17374833890481012), (156447, 0.08783893363801018), (233917, 0.06809283470155628), (157332, 0.0665280213300044), (166430, 0.06590535715208987)]
[(199197, 0.21958335546554147), (206934, 0.18048072331360698), (166582, 0.12273663228009231), (33627, 0.11751137885968198), (313431, 0.1174601891450195), (284410, 0.09726647981437406), (237334, 0.09616375999807694), (264790, 0.0802139951322084), (283013, 0.0802139951322084), (285298, 0.07962688629227777)]
[(199198, 0.2742467191433369), (64329, 0.26765077763116946), (182513, 0.24996876218991318), (175040, 0.23089396142175667), (348111, 0.19779372480578833), (198659, 0.16417387594471664), (156624, 0.16240321436422347), (284474, 0.16145238513086735), (233917, 0.1148109975134215), (341838, 0.10715630398092232)]
[(65794, 0.19406365517181853), (156624, 0.1873026677869342), (272143, 0.1564547338213162), (292708, 0.15610473950771406), (158704, 0.15379180810010684), (191903, 0.15379180810010684), (160417, 0.1532838659616381), (50864, 0.15074178380379075), (166430, 0.14503936835485431), (50383, 0.13514557010693226)]
[(156560, 0.1964275841390113), (158536, 0.1832251919447172), (162765, 0.1813363905861373), (157332, 0.15690440665465014), (160974, 0.14414482050765215), (156447, 0.1242218685419651), (204678, 0.10441160008718423), (206566, 0.10441160008718423), (162655, 0.0938444249093069), (272143, 0.08526492529654099)]
[(235230, 0.2973104973666827), (284547, 0.20318641990544245), (83565, 0.17603078872303546), (187065, 0.1460490271720965), (158192, 0.1442231472937707), (84371, 0.13536170965002617), (129029, 0.13385712470511854), (206934, 0.1331379500256803), (58193, 0.12745898607466183), (111210, 0.12019525564421114)]
[(156624, 0.1369881430866801), (272143, 0.1042388584525598), (156447, 0.08783893363801018), (156025, 0.07603670497064792), (64329, 0.07545421476168913), (160417, 0.0722104053646523), (157332, 0.0665280213300044), (166430, 0.06590535715208987), (162655, 0.06263948773013987), (199197, 0.06068921248587873)]
[(297941, 0.32181816482491765), (111809, 0.32181816482491765), (182469, 0.19732190434332983), (181486, 0.19732190434332983), (182023, 0.19732190434332983), (83592, 0.12847458559243768), (178365, 0.11392385458963109), (84721, 0.10489905987233188), (79376, 0.10489905987233188), (160974, -100)]
[(336476, 0.32710705125759565), (162765, 0.1813363905861373), (156560, 0.1369881430866801), (156447, 0.1242218685419651), (348111, 0.12241980393274354), (158229, 0.11101658048608612), (157332, 0.08976206393186344), (272143, 0.08526492529654099), (160417, 0.08042054203791298), (337890, 0.07324417494371821)]
[(160974, 0.1543543858956076), (158536, 0.11041310336685785), (162655, 0.0938444249093069), (206402, 0.09161122670772169), (156624, 0.08042054203791298), (158082, 0.0706363249823161), (166283, 0.06770619354744825), (157332, 0.0671423427227867), (162300, 0.06107580452411221), (156560, 0.0594394410523312)]
[(199198, 0.2742467191433369), (336476, 0.26161809706248934), (156560, 0.24122700153923987), (64329, 0.19735844511100942), (162765, 0.1813363905861373), (198659, 0.16417387594471664), (348111, 0.1620880909036662), (175040, 0.14832189638870905), (299767, 0.1289882580222607), (156447, 0.1242218685419651)]
[(272143, 0.2742467191433369), (64329, 0.2205925817690975), (175040, 0.1845285420073168), (198659, 0.16133250919593656), (2303, 0.13931112187139225), (182394, 0.11014153830293937), (36161, 0.10310208986501465), (36129, 0.08028034417637815), (224658, 0.06632827488421664), (35908, 0.0640092417817584)]
[(199198, 0.46450327764417554), (272143, 0.42707803644059783), (336476, 0.2692604274181166), (182513, 0.1771087814230476), (284474, 0.08069039596278683), (348134, 0.07568701341748939), (156560, 0.07545421476168913), (233917, 0.06416618965038366), (328760, 0.05581034781872852), (315099, 0.054494597071643704)]
[(64329, 0.4179510268801069), (175040, 0.33285043839602585), (198659, 0.3255063851406532), (336476, 0.1486341379702074), (348111, 0.14077984880864058), (182394, 0.11014153830293937), (156560, 0.1042388584525598), (156624, 0.08526492529654099), (324823, 0.08504076711209806), (284474, 0.07075792228133822)]
[(64329, 0.4179510268801069), (175040, 0.33285043839602585), (198659, 0.3255063851406532), (336476, 0.1486341379702074), (348111, 0.14077984880864058), (182394, 0.11014153830293937), (156560, 0.1042388584525598), (156624, 0.08526492529654099), (324823, 0.08504076711209806), (284474, 0.07075792228133822)]
[(199198, 0.2742467191433369), (64329, 0.19735844511100942), (156560, 0.16687834618269967), (198659, 0.16417387594471664), (175040, 0.14832189638870905), (156624, 0.1355794499967951), (160417, 0.0938444249093069), (336476, 0.09378534514527773), (158536, 0.08967731152361727), (160974, 0.0865198721131068)]
[(272143, 0.47160516425434634), (175040, 0.4260683003395364), (304302, 0.3222253204769533), (33495, 0.3222253204769533), (156216, 0.29669934630327804), (198659, 0.2062486145887856), (336476, 0.1251411253450897), (2303, 0.121789723444301), (182394, 0.11014153830293937), (348111, 0.10988935039437231)]
[(336476, 0.30481755501484287), (272143, 0.2742467191433369), (64329, 0.2205925817690975), (175040, 0.1845285420073168), (348111, 0.1818019578005048), (198659, 0.16133250919593656), (182394, 0.11014153830293937), (233917, 0.06809283470155628), (224658, 0.06632827488421664), (156624, 0.06058175472028041)]
[(283552, 0.20711164485320396), (357715, 0.17851259917722495), (128419, 0.17851259917722495), (282539, 0.17851259917722495), (226101, 0.06660560348705334), (215839, 0.06660560348705334), (215770, 0.06660560348705334), (285343, 0.05696403594023164), (195839, 0.05472724952939048), (201768, 0.0489495400677242)]
[(67542, 0.45511961331341866), (297941, 0.32181816482491765), (182469, 0.19732190434332983), (181486, 0.19732190434332983), (182023, 0.19732190434332983), (83592, 0.12847458559243768), (178365, 0.11392385458963109), (84721, 0.10489905987233188), (79376, 0.10489905987233188), (160974, -100)]
[(156560, 0.22482707672469027), (162765, 0.1813363905861373), (157332, 0.14044105998906584), (160417, 0.13229798097224488), (158229, 0.11101658048608612), (107039, 0.0972614455180946), (272143, 0.08526492529654099), (336476, 0.07713828906768248), (337890, 0.07324417494371821), (158536, 0.07281208857785937)]
[(199198, 0.2742467191433369), (64329, 0.27281265987269854), (198659, 0.2227108520254729), (156624, 0.22225306838322106), (50864, 0.15074178380379075), (175040, 0.14832189638870905), (50383, 0.13514557010693226), (161160, 0.10840791429656242), (336476, 0.09378534514527773), (156447, 0.08783893363801018)]
[(206934, 0.3865246092456601), (199198, 0.2742467191433369), (336801, 0.21308562285528926), (336476, 0.20859634265869922), (208199, 0.20353567865244448), (64329, 0.19735844511100942), (160132, 0.17982020908007929), (161602, 0.16867723241014831), (285218, 0.16618618571652527), (198659, 0.16417387594471664)]
[(199198, 0.33362887301109817), (31267, 0.22811011491194377), (336476, 0.2101813750101867), (31677, 0.20353567865244448), (64329, 0.19735844511100942), (111587, 0.17649007662455862), (198659, 0.16417387594471664), (316168, 0.15207340994129584), (284474, 0.15144831824412505), (175040, 0.14832189638870905)]
[(272143, 0.16417387594471664), (199198, 0.16133250919593656), (13811, 0.11211930324396888), (182394, 0.08401137703392705), (118753, 0.07767529402182977), (7694, 0.07431102627934141), (324823, 0.06416636774431653), (156560, 0.05853697608075625), (199406, 0.05848288387800043), (160974, -100)]
[(199198, 0.2742467191433369), (64329, 0.26765077763116946), (182513, 0.24996876218991318), (175040, 0.23089396142175667), (348111, 0.19779372480578833), (198659, 0.16417387594471664), (156624, 0.16240321436422347), (284474, 0.16145238513086735), (233917, 0.1148109975134215), (341838, 0.10715630398092232)]
[(156560, 0.3006664425915711), (199198, 0.2742467191433369), (64329, 0.19735844511100942), (158536, 0.1832251919447172), (162765, 0.1813363905861373), (336476, 0.1709236342129602), (198659, 0.16417387594471664), (157332, 0.15690440665465014), (175040, 0.14832189638870905), (160974, 0.14414482050765215)]
[(64329, 0.4179510268801069), (336476, 0.39860290016012057), (175040, 0.33285043839602585), (198659, 0.3255063851406532), (348111, 0.2631996527413841), (156624, 0.1458466800168214), (284474, 0.1280194618547869), (182394, 0.11014153830293937), (156560, 0.1042388584525598), (324823, 0.08504076711209806)]
[(50383, 0.13514557010693226), (50815, 0.12871776892689038), (87203, 0.10945449905878096), (161160, 0.10840791429656242), (105121, 0.1007837567594748), (50619, 0.07762341432436974), (5408, 0.07718967948100029), (200521, 0.07665597133338936), (293264, 0.07665597133338936), (68577, 0.07665597133338936)]
[(199198, 0.2742467191433369), (156560, 0.24122700153923987), (64329, 0.19735844511100942), (162765, 0.1813363905861373), (336476, 0.1709236342129602), (198659, 0.16417387594471664), (175040, 0.14832189638870905), (187065, 0.1460490271720965), (129029, 0.13385712470511854), (313431, 0.13263587579461047)]
[(272143, 0.7013247555839347), (336476, 0.3241092202430463), (182513, 0.23434342232263938), (198659, 0.2062486145887856), (31267, 0.1316994362492872), (97661, 0.11343971980809854), (100954, 0.11343971980809854), (182394, 0.11014153830293937), (96288, 0.09382457146014178), (32714, 0.09312556445031639)]
[(199198, 0.4587752611506537), (64329, 0.43889820344322905), (336476, 0.17635741017832535), (198659, 0.16417387594471664), (348111, 0.13272622991294591), (31267, 0.1316994362492872), (324823, 0.12228561758866816), (97661, 0.11343971980809854), (100954, 0.11343971980809854), (156560, 0.1042388584525598)]
[(162765, 0.1813363905861373), (156560, 0.1369881430866801), (156447, 0.1242218685419651), (204678, 0.10441160008718423), (206566, 0.10441160008718423), (157332, 0.08976206393186344), (272143, 0.08526492529654099), (80055, 0.0827442353892404), (272401, 0.0827442353892404), (123253, 0.0827442353892404)]
[(182513, 0.3723885661226567), (233917, 0.17897718716380517), (272143, 0.1751830400861571), (284474, 0.17138485881231597), (341838, 0.10715630398092232), (175040, 0.0825720650330476), (156624, 0.07713828906768248), (348134, 0.07568701341748939), (64329, 0.07029233252016003), (199198, 0.059382153867761245)]
[(199198, 0.2742467191433369), (64329, 0.19735844511100942), (198659, 0.16417387594471664), (50864, 0.15074178380379075), (175040, 0.14832189638870905), (50383, 0.13514557010693226), (161160, 0.10840791429656242), (156560, 0.1042388584525598), (336476, 0.09378534514527773), (156624, 0.08526492529654099)]
[(182513, 0.24996876218991318), (187065, 0.22090699981626677), (129029, 0.2134840109973963), (313431, 0.13263587579461047), (348111, 0.11639602986490896), (233917, 0.1148109975134215), (235230, 0.11110277035639192), (341838, 0.10715630398092232), (289444, 0.10240991408261158), (13498, 0.10240991408261158)]
[(199198, 0.49483930091243444), (175040, 0.38986165472092865), (198659, 0.20908998133756568), (156560, 0.17969307321424893), (336476, 0.16407767766543774), (156624, 0.13490297352275948), (348111, 0.13190489146749043), (324823, 0.08504076711209806), (284474, 0.07075792228133822), (72256, 0.04290908864332235)]
[(64329, 0.4882433594002669), (175040, 0.41542250342907344), (198659, 0.3255063851406532), (182513, 0.30720340308950495), (348111, 0.2571758786735495), (156624, 0.16240321436422347), (284474, 0.16145238513086735), (233917, 0.1148109975134215), (182394, 0.11014153830293937), (341838, 0.10715630398092232)]
[(272143, 0.47160516425434634), (175040, 0.4260683003395364), (198659, 0.2062486145887856), (336476, 0.1251411253450897), (182394, 0.11014153830293937), (348111, 0.10988935039437231), (156560, 0.07545421476168913), (224658, 0.06632827488421664), (182513, 0.057234640899591786), (261612, 0.055850874376048784)]
[(156447, 0.2214833140600597), (157332, 0.20552684376435587), (156560, 0.19962763081681995), (162765, 0.1813363905861373), (160417, 0.17426496694721988), (158229, 0.16980770138671594), (158536, 0.16248940010147664), (263693, 0.15845231093012707), (272143, 0.1374808006652974), (263964, 0.08879174180575594)]
[(313431, 0.23962063292607946), (271551, 0.22344611717259244), (187065, 0.1967503916199284), (161602, 0.175818163783852), (289126, 0.17129944745658357), (84371, 0.1395276566378118), (58606, 0.13882339503596353), (129029, 0.13385712470511854), (284421, 0.13138171562999032), (140699, 0.11377990332835466)]
[(199198, 0.2742467191433369), (64329, 0.19735844511100942), (156560, 0.16687834618269967), (198659, 0.16417387594471664), (175040, 0.14832189638870905), (156624, 0.1355794499967951), (160417, 0.0938444249093069), (336476, 0.09378534514527773), (158536, 0.08967731152361727), (160974, 0.0865198721131068)]
[(64329, 0.4179510268801069), (175040, 0.33285043839602585), (198659, 0.3255063851406532), (336476, 0.1486341379702074), (348111, 0.14077984880864058), (182394, 0.11014153830293937), (156560, 0.1042388584525598), (156624, 0.08526492529654099), (324823, 0.08504076711209806), (284474, 0.07075792228133822)]

 37%|███▋      | 2866/7721 [00:00<00:00, 5866.86it/s]

[(272143, 0.6280598980756625), (175040, 0.4260683003395364), (198659, 0.2647855906695419), (156624, 0.2369407160131527), (182394, 0.15599021573134333), (160417, 0.1532838659616381), (336476, 0.1251411253450897), (157332, 0.11168702164090244), (348111, 0.10988935039437231), (158536, 0.08967731152361727)]
[(199198, 0.2742467191433369), (118773, 0.21967507280760062), (118878, 0.21967507280760062), (118948, 0.21967507280760062), (118627, 0.21967507280760062), (64329, 0.19735844511100942), (198659, 0.16417387594471664), (175040, 0.14832189638870905), (118726, 0.12682946241971887), (96663, 0.11377990332835466)]
[(199198, 0.4587752611506537), (64329, 0.43889820344322905), (336476, 0.17635741017832535), (198659, 0.16417387594471664), (348111, 0.13272622991294591), (324823, 0.12228561758866816), (156560, 0.1042388584525598), (156624, 0.08526492529654099), (284474, 0.07075792228133822), (328760, 0.05581034781872852)]
[(199198, 0.49483930091243444), (175040, 0.38986165472092865), (198659, 0.20908998133756568), (156560, 0.17969307321424893), (336476, 0.16407767766543774), (156624, 0.13490297352275948), (348111, 0.13190489146749043), (324823, 0.08504076711209806), (284474, 0.07075792228133822), (72256, 0.04290908864332235)]
[(356695, 0.20882320017436845), (284312, 0.17253766289901798), (284629, 0.1397904821071109), (213927, 0.09745173021303453), (285023, 0.07826243580495225), (293425, 0.07362222301295154), (159762, 0.06806749827108248), (160974, 0.06709833887801207), (293301, 0.05894818267481078), (70023, 0.05696192729481554)]
[(166445, 0.17023830305046592), (95706, 0.12847458559243768), (215641, 0.11038271988126416), (285218, 0.11038271988126416), (85767, 0.10655806217658674), (211484, 0.0908452506825442), (166534, 0.0908452506825442), (31960, 0.08247338610152372), (114824, 0.06498478953752444), (220553, 0.06498478953752444)]
[(199198, 0.2742467191433369), (64329, 0.19735844511100942), (156560, 0.17014421560464965), (198659, 0.16417387594471664), (175040, 0.14832189638870905), (164013, 0.11038271988126416), (336476, 0.09378534514527773), (156624, 0.08526492529654099), (324823, 0.08504076711209806), (348111, 0.08139769494087935)]
[(272143, 0.635779040199063), (175040, 0.4260683003395364), (182394, 0.1941529153368664), (156560, 0.13399119084244537), (336476, 0.1251411253450897), (13811, 0.11211930324396888), (348111, 0.10988935039437231), (118753, 0.07767529402182977), (7694, 0.07431102627934141), (169111, 0.07022648096771238)]
[(140450, 0.19732190434332983), (275190, 0.1894615908449756), (275189, 0.18307359666251405), (66171, 0.12479732999335877), (32486, 0.10938570047544141), (336476, 0.09069446284952913), (283327, 0.09016612023797267), (348111, 0.08069039596278683), (275192, 0.07775616900834297), (278808, 0.07585326888556977)]
[(182513, 0.24996876218991318), (348111, 0.11639602986490896), (233917, 0.1148109975134215), (341838, 0.10715630398092232), (272143, 0.09378534514527773), (284474, 0.09069446284952913), (175040, 0.0825720650330476), (156624, 0.07713828906768248), (64329, 0.07029233252016003), (4967, 0.05869249737321499)]
[(336476, 0.20709049271443808), (272143, 0.15215561722221757), (182513, 0.12241980393274354), (275192, 0.07775616900834297), (232753, 0.07585326888556977), (278808, 0.07585326888556977), (279159, 0.07585326888556977), (348134, 0.07568701341748939), (275189, 0.07368789618707264), (233917, 0.06416618965038366)]
[(199198, 0.2742467191433369), (64329, 0.19735844511100942), (285648, 0.18481089989236407), (198659, 0.16417387594471664), (175040, 0.14832189638870905), (336607, 0.11134994710096138), (156560, 0.1042388584525598), (336476, 0.09378534514527773), (156624, 0.08526492529654099), (324823, 0.08504076711209806)]
[(64329, 0.4621323401013171), (272143, 0.42256861553204594), (198659, 0.16133250919593656), (336476, 0.13742085785797725), (182513, 0.11192361838989583), (348111, 0.11071068883982782), (182394, 0.11014153830293937), (224658, 0.06632827488421664), (261612, 0.055850874376048784), (328760, 0.05581034781872852)]
[(336476, 0.36636479205482214), (284474, 0.13795193553623553), (233917, 0.13225902435193992), (199198, 0.11661679476735304), (272143, 0.08139769494087935), (348134, 0.07568701341748939), (156624, 0.06058175472028041), (237443, 0.05963175442672755), (180124, 0.05963175442672755), (184238, 0.05963175442672755)]
[(202557, -91), (162655, -92), (158536, -93), (199198, -94), (160417, -95), (16129, -96), (156624, -97), (300470, -98), (272143, -99), (160974, -100)]
[(182513, 0.24996876218991318), (348111, 0.1970864258276958), (272143, 0.16454326742661596), (156624, 0.13646298005970775), (233917, 0.1148109975134215), (341838, 0.10715630398092232), (175040, 0.0825720650330476), (275192, 0.07775616900834297), (232753, 0.07585326888556977), (278808, 0.07585326888556977)]
[(135769, 0.35872789172491043), (285648, 0.18481089989236407), (336607, 0.11134994710096138), (140324, 0.08455297494647925), (260394, 0.07748470862188879), (292558, 0.07748470862188879), (245107, 0.07748470862188879), (172423, 0.07748470862188879), (78376, 0.06211344592022867), (236065, 0.0614051787724995)]
[(64329, 0.4179510268801069), (175040, 0.33285043839602585), (198659, 0.3255063851406532), (336476, 0.1486341379702074), (348111, 0.14077984880864058), (182394, 0.11014153830293937), (156560, 0.1042388584525598), (156624, 0.08526492529654099), (324823, 0.08504076711209806), (284474, 0.07075792228133822)]
[(351411, 0.17201904480216956), (199197, 0.11110277035639192), (313431, 0.10698475713146899), (235827, 0.10113769184742637), (288841, 0.09194804709283362), (70646, 0.08409954033602747), (206934, 0.08146138019435344), (190559, 0.0801497244938313), (271551, 0.07922296987882174), (264825, 0.07426372897645614)]
[(199198, 0.2742467191433369), (64329, 0.27281265987269854), (198659, 0.2227108520254729), (156624, 0.22225306838322106), (175040, 0.14832189638870905), (2303, 0.13931112187139225), (336476, 0.09378534514527773), (156447, 0.08783893363801018), (324823, 0.08504076711209806), (348111, 0.08139769494087935)]
[(199198, 0.4051211237764143), (272143, 0.3456803414997185), (336476, 0.15286439755320763), (348111, 0.10183573149867764), (156560, 0.07545421476168913), (328760, 0.05581034781872852), (182513, 0.05468897749030404), (156624, 0.04963804822621849), (198659, 0.04491610539284904), (72256, 0.04290908864332235)]
[(162765, 0.1813363905861373), (50864, 0.15074178380379075), (156560, 0.1369881430866801), (50383, 0.13514557010693226), (156447, 0.1242218685419651), (158229, 0.11101658048608612), (161160, 0.10840791429656242), (157332, 0.08976206393186344), (272143, 0.08526492529654099), (160417, 0.08042054203791298)]
[(336476, 0.36636479205482214), (284474, 0.13795193553623553), (233917, 0.13225902435193992), (199198, 0.11661679476735304), (272143, 0.08139769494087935), (348134, 0.07568701341748939), (156624, 0.06058175472028041), (237443, 0.05963175442672755), (180124, 0.05963175442672755), (184238, 0.05963175442672755)]
[(156560, 0.2629556054690157), (158536, 0.1832251919447172), (162765, 0.1813363905861373), (160974, 0.14414482050765215), (156447, 0.1242218685419651), (158229, 0.11101658048608612), (162655, 0.0938444249093069), (272143, 0.08526492529654099), (336476, 0.07713828906768248), (337890, 0.07324417494371821)]
[(64329, 0.4179510268801069), (175040, 0.33285043839602585), (198659, 0.3255063851406532), (336476, 0.1486341379702074), (348111, 0.14077984880864058), (182394, 0.11014153830293937), (156560, 0.1042388584525598), (156624, 0.08526492529654099), (324823, 0.08504076711209806), (284474, 0.07075792228133822)]
[(64329, 0.4179510268801069), (175040, 0.33285043839602585), (264664, 0.28784291717709903), (156560, 0.19645963581751857), (182394, 0.1941529153368664), (324823, 0.14920713485641457), (336476, 0.1486341379702074), (348111, 0.14077984880864058), (13811, 0.11211930324396888), (264195, 0.10753213940765202)]
[(272143, 0.4316110252830876), (64329, 0.38728630561406874), (348111, 0.29014436876971905), (199198, 0.2417631829069086), (156447, 0.21206080217997528), (233917, 0.18290383221497777), (162765, 0.1813363905861373), (157332, 0.15629008526186783), (284474, 0.14795600242297782), (160417, 0.13985998309024417)]
[(348111, 0.2388158337976525), (233917, 0.18290383221497777), (284474, 0.14795600242297782), (156624, 0.1377200437879629), (341838, 0.10715630398092232), (272143, 0.09378534514527773), (175040, 0.0825720650330476), (64329, 0.07029233252016003), (237443, 0.05963175442672755), (180124, 0.05963175442672755)]
[(97485, 0.20882320017436845), (97480, 0.1654884707784808), (96960, 0.15623548541982177), (299767, 0.1289882580222607), (95742, 0.11032564718565388), (91369, 0.09963398728176989), (96954, 0.09963398728176989), (96481, 0.09112645567325996), (95680, 0.09053749898732362), (91361, 0.08525171448037899)]
[(336476, 0.19353431893259143), (162765, 0.1813363905861373), (272143, 0.16666262023742034), (156560, 0.1369881430866801), (156447, 0.1242218685419651), (182513, 0.12241980393274354), (158229, 0.11101658048608612), (157332, 0.08976206393186344), (284474, 0.08069039596278683), (160417, 0.08042054203791298)]
[(284547, 0.19924753158134315), (285298, 0.15499241073990627), (187065, 0.1460490271720965), (313431, 0.13263587579461047), (166582, 0.12273663228009231), (235230, 0.11110277035639192), (284410, 0.09726647981437406), (237334, 0.09616375999807694), (206934, 0.08720266286265492), (218098, 0.07638557905756371)]
[(199198, 0.49483930091243444), (175040, 0.38986165472092865), (198659, 0.20908998133756568), (156560, 0.17969307321424893), (336476, 0.16407767766543774), (156624, 0.13490297352275948), (348111, 0.13190489146749043), (324823, 0.08504076711209806), (284474, 0.07075792228133822), (72256, 0.04290908864332235)]
[(199198, 0.49483930091243444), (175040, 0.38986165472092865), (198659, 0.20908998133756568), (156560, 0.17969307321424893), (336476, 0.16407767766543774), (156624, 0.13490297352275948), (348111, 0.13190489146749043), (324823, 0.08504076711209806), (284474, 0.07075792228133822), (72256, 0.04290908864332235)]
[(160417, 0.250273086457102), (156447, 0.21206080217997528), (272143, 0.1895037837491008), (162765, 0.1813363905861373), (160974, 0.159090992507536), (157332, 0.15629008526186783), (162655, 0.15231679925375713), (158229, 0.11101658048608612), (166283, 0.09179702964358943), (336476, 0.07713828906768248)]
[(156624, 0.21398393247382852), (107039, 0.16786722503968898), (156560, 0.15436695496801459), (160417, 0.1190197816571186), (273054, 0.07241474470854635), (68668, 0.07241474470854635), (39639, 0.07241474470854635), (208077, 0.06617794653087158), (167259, 0.06484267591277695), (136075, 0.06349647765735983)]
[(162765, 0.1813363905861373), (336476, 0.16783275191721161), (272143, 0.1560228475778792), (156560, 0.1369881430866801), (156447, 0.1242218685419651), (158229, 0.11101658048608612), (157332, 0.08976206393186344), (348111, 0.08069039596278683), (160417, 0.08042054203791298), (275192, 0.07775616900834297)]
[(227555, 0.3034130755422791), (319716, 0.3034130755422791), (272143, 0.2459409623674953), (156624, 0.19704473477998816), (236593, 0.1605022113395666), (234991, 0.11957596390830347), (199198, 0.11661679476735304), (341838, 0.10715630398092232), (282959, 0.1023641910618959), (236370, 0.09088124514043709)]
[(156624, 0.1369881430866801), (164013, 0.11038271988126416), (272143, 0.1042388584525598), (156447, 0.08783893363801018), (224171, 0.07913401120276446), (341092, 0.07805236975385703), (236897, 0.07805236975385703), (286418, 0.07805236975385703), (64329, 0.07545421476168913), (85767, 0.07534792835516226)]
[(199198, 0.2742467191433369), (64329, 0.19735844511100942), (198659, 0.16417387594471664), (175040, 0.14832189638870905), (156560, 0.1042388584525598), (336476, 0.09378534514527773), (156624, 0.08526492529654099), (324823, 0.08504076711209806), (348111, 0.08139769494087935), (284474, 0.07075792228133822)]
[(199198, 0.2742467191433369), (64329, 0.26765077763116946), (182513, 0.24996876218991318), (156560, 0.24122700153923987), (175040, 0.23089396142175667), (348111, 0.19779372480578833), (162765, 0.1813363905861373), (198659, 0.16417387594471664), (284474, 0.16145238513086735), (156447, 0.1242218685419651)]
[(175040, 0.5743901967282454), (198659, 0.37042249053350224), (336476, 0.2189264704903674), (348111, 0.19128704533525168), (156560, 0.17969307321424893), (156624, 0.13490297352275948), (182394, 0.11014153830293937), (324823, 0.08504076711209806), (284474, 0.07075792228133822), (224658, 0.06632827488421664)]
[(162765, 0.1813363905861373), (107301, 0.1786889993417549), (156560, 0.1369881430866801), (156447, 0.1242218685419651), (158229, 0.11101658048608612), (207469, 0.09464216817386983), (157332, 0.08976206393186344), (272143, 0.08526492529654099), (160417, 0.08042054203791298), (50823, 0.07718967948100029)]
[(182513, 0.12241980393274354), (289456, 0.11850305364657529), (336476, 0.11639602986490896), (336607, 0.11134994710096138), (272143, 0.08139769494087935), (284474, 0.08069039596278683), (260394, 0.07748470862188879), (292558, 0.07748470862188879), (245107, 0.07748470862188879), (172423, 0.07748470862188879)]
[(250110, 0.26276343125998064), (129147, 0.26276343125998064), (125848, 0.26276343125998064), (342100, 0.2507400360344115), (199197, 0.20922264915274702), (166582, 0.12273663228009231), (284547, 0.1135213008209202), (289444, 0.10240991408261158), (13498, 0.10240991408261158), (285939, 0.1023641910618959)]
[(162765, 0.2677115882770056), (156560, 0.1369881430866801), (156447, 0.1242218685419651), (158229, 0.11101658048608612), (157332, 0.08976206393186344), (272143, 0.08526492529654099), (160417, 0.08042054203791298), (336476, 0.07713828906768248), (337890, 0.07324417494371821), (158536, 0.07281208857785937)]
[(202528, 0.14575492688072578), (289456, 0.11850305364657529), (83792, 0.11550804670065219), (336607, 0.11134994710096138), (284901, 0.09745173021303453), (284629, 0.08616365253045165), (353593, 0.08616365253045165), (260394, 0.07748470862188879), (292558, 0.07748470862188879), (245107, 0.07748470862188879)]
[(199198, 0.2742467191433369), (64329, 0.19735844511100942), (156560, 0.16687834618269967), (198659, 0.16417387594471664), (175040, 0.14832189638870905), (156624, 0.1355794499967951), (160417, 0.0938444249093069), (336476, 0.09378534514527773), (158536, 0.08967731152361727), (160974, 0.0865198721131068)]
[(162765, 0.1813363905861373), (156560, 0.1369881430866801), (156447, 0.1242218685419651), (158229, 0.11101658048608612), (149599, 0.10344421877083577), (224857, 0.10306429718871057), (157332, 0.08976206393186344), (272143, 0.08526492529654099), (63736, 0.08517215530270575), (65831, 0.08517215530270575)]
[(313431, 0.26577382582029074), (161602, 0.25157695652120987), (129029, 0.22105978756777345), (208199, 0.20353567865244448), (235230, 0.19256415055074536), (284547, 0.179004291211375), (338350, 0.1782915674496761), (187065, 0.1460490271720965), (70646, 0.13281063066935003), (150326, 0.12022458674074694)]
[(175040, 0.5743901967282454), (198659, 0.37042249053350224), (336476, 0.21892647049036743), (348111, 0.19128704533525165), (156560, 0.17969307321424893), (156624, 0.13490297352275948), (182394, 0.11014153830293937), (324823, 0.08504076711209806), (284474, 0.07075792228133822), (224658, 0.06632827488421664)]
[(202557, -91), (162655, -92), (158536, -93), (199198, -94), (160417, -95), (16129, -96), (156624, -97), (300470, -98), (272143, -99), (160974, -100)]
[(64329, 0.4179510268801069), (175040, 0.33285043839602585), (198659, 0.3255063851406532), (336476, 0.1486341379702074), (348111, 0.14077984880864058), (182394, 0.11014153830293937), (156560, 0.1042388584525598), (156624, 0.08526492529654099), (324823, 0.08504076711209806), (284474, 0.07075792228133822)]
[(64329, 0.6594907852123265), (198659, 0.3255063851406532), (336476, 0.231206203003255), (348111, 0.19210838378070716), (324823, 0.12228561758866816), (182513, 0.11192361838989583), (182394, 0.11014153830293937), (156560, 0.1042388584525598), (156624, 0.08526492529654099), (284474, 0.07075792228133822)]
[(64329, 0.4179510268801069), (175040, 0.33285043839602585), (198659, 0.3255063851406532), (336476, 0.1486341379702074), (348111, 0.14077984880864058), (182394, 0.11014153830293937), (156560, 0.1042388584525598), (156624, 0.08526492529654099), (324823, 0.08504076711209806), (284474, 0.07075792228133822)]
[(199198, 0.2742467191433369), (64329, 0.19735844511100942), (156560, 0.17014421560464965), (198659, 0.16417387594471664), (175040, 0.14832189638870905), (2303, 0.13931112187139225), (164013, 0.11038271988126416), (36161, 0.10310208986501465), (336476, 0.09378534514527773), (156624, 0.08526492529654099)]
[(272143, 0.35564441408421626), (64329, 0.2205925817690975), (175040, 0.1845285420073168), (182513, 0.17965444483233534), (336476, 0.17124482268983862), (198659, 0.16133250919593656), (182394, 0.11014153830293937), (284474, 0.08069039596278683), (348134, 0.07568701341748939), (224658, 0.06632827488421664)]
[(199198, 0.2742467191433369), (64329, 0.19735844511100942), (336476, 0.18447980799480684), (198659, 0.16417387594471664), (348111, 0.1620880909036662), (175040, 0.14832189638870905), (156624, 0.14458961628856626), (156560, 0.1042388584525598), (324823, 0.08504076711209806), (275192, 0.07775616900834297)]
[(285648, 0.18481089989236407), (299767, 0.1289882580222607), (336607, 0.11134994710096138), (96481, 0.09112645567325996), (95743, 0.07951169611730846), (260394, 0.07748470862188879), (292558, 0.07748470862188879), (245107, 0.07748470862188879), (172423, 0.07748470862188879), (95756, 0.07205177206581224)]
[(298046, 0.19278823416444013), (225198, 0.13632186771065563), (234000, 0.10852105599206949), (330745, 0.09570657538971056), (352092, 0.09194804709283362), (209294, 0.08621751937076709), (16841, 0.0544623123019677), (96077, 0.04446816369843362), (70033, 0.043108759685383545), (160974, -100)]
[(199198, 0.2742467191433369), (64329, 0.19735844511100942), (198659, 0.16417387594471664), (175040, 0.14832189638870905), (169156, 0.11789636534962156), (66206, 0.10441160008718423), (50626, 0.10441160008718423), (156560, 0.1042388584525598), (336476, 0.09378534514527773), (65753, 0.09367120004034671)]
[(268377, 0.7500176128950071), (72612, 0.7500176128950071), (123253, 0.36067376022224085), (158229, 0.0413721176946202), (199198, 0.01819023815823432), (16129, -96), (156624, -97), (300470, -98), (272143, -99), (160974, -100)]
[(199198, 0.2742467191433369), (64329, 0.19735844511100942), (285343, 0.18481089989236407), (198659, 0.16417387594471664), (175040, 0.14832189638870905), (289456, 0.11850305364657529), (156560, 0.1042388584525598), (336476, 0.09378534514527773), (156624, 0.08526492529654099), (324823, 0.08504076711209806)]
[(162765, 0.1813363905861373), (50864, 0.15074178380379075), (156560, 0.1369881430866801), (50383, 0.13514557010693226), (337854, 0.13138171562999032), (156447, 0.1242218685419651), (199418, 0.11941032891859625), (136465, 0.11392385458963109), (158229, 0.11101658048608612), (161160, 0.10840791429656242)]
[(107301, 0.1786889993417549), (50864, 0.15074178380379075), (50383, 0.13514557010693226), (161160, 0.10840791429656242), (207469, 0.09464216817386983), (50619, 0.07762341432436974), (200521, 0.07665597133338936), (293264, 0.07665597133338936), (68577, 0.07665597133338936), (61938, 0.07665597133338936)]
[(156624, 0.3612393666660133), (160974, 0.30323581301518815), (272143, 0.2684127343972764), (162655, 0.24616122416306407), (199198, 0.16133250919593656), (166283, 0.15950322319103769), (187065, 0.1460490271720965), (162300, 0.1339870574474143), (129029, 0.13385712470511854), (157332, 0.1336703640527911)]
[(199198, 0.49483930091243444), (175040, 0.38986165472092865), (198659, 0.24787503639547995), (156560, 0.17969307321424893), (336476, 0.16407767766543774), (156624, 0.13490297352275948), (348111, 0.13190489146749043), (119044, 0.11315185234737829), (273394, 0.11315185234737829), (206159, 0.11315185234737829)]

 45%|████▍     | 3454/7721 [00:00<00:00, 5226.41it/s]

[(156624, 0.34647493692518616), (199198, 0.2742467191433369), (64329, 0.27281265987269854), (198659, 0.2227108520254729), (175040, 0.14832189638870905), (337854, 0.13138171562999032), (199418, 0.11941032891859625), (157332, 0.11720701738720682), (160417, 0.11131687998666309), (107039, 0.0972614455180946)]
[(237055, 0.18382237252265904), (292708, 0.15610473950771406), (272143, 0.13367551387968202), (299767, 0.1289882580222607), (70673, 0.12371007915228557), (225514, 0.11038271988126416), (342917, 0.11038271988126416), (96481, 0.09112645567325996), (336476, 0.09069446284952913), (223931, 0.09012711337655513)]
[(162765, 0.1813363905861373), (161584, 0.17466544787793511), (156560, 0.1369881430866801), (156447, 0.1242218685419651), (158229, 0.11101658048608612), (158722, 0.09703182758590927), (157332, 0.08976206393186344), (159581, 0.08696386581798134), (272143, 0.08526492529654099), (160417, 0.08042054203791298)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (158536, 0.23190308108539537), (160417, 0.22456536254556514), (162300, 0.21585021382334774), (162765, 0.1813363905861373), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (156560, 0.1369881430866801), (59758, 0.12538033733281437)]
[(159084, 0.2174944607970515), (233478, 0.15494618018418746), (160974, 0.14414482050765215), (203153, 0.11898958538640447), (160437, 0.1175506033679205), (114824, 0.11424963800302142), (220553, 0.11424963800302142), (158536, 0.11041310336685785), (162655, 0.0938444249093069), (159762, 0.08945821883924489)]
[(299767, 0.1289882580222607), (236065, 0.12371007915228557), (233728, 0.11791129580380143), (242485, 0.11038271988126416), (234980, 0.10655806217658674), (96481, 0.09112645567325996), (236370, 0.09017405551742477), (61790, 0.09012711337655513), (156157, 0.08813283862349285), (31960, 0.08247338610152372)]
[(272143, 0.2742467191433369), (198659, 0.2453438862298636), (64329, 0.2205925817690975), (175040, 0.1845285420073168), (224658, 0.13244499563569917), (118864, 0.08881146774652446), (220258, 0.060853212265398166), (50629, 0.06063608079621973), (105327, 0.06063608079621973), (313137, 0.06063608079621973)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (160417, 0.20358426155998335), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (156624, 0.1369881430866801), (59758, 0.12538033733281437), (272143, 0.1042388584525598)]
[(199197, 0.17179198284227065), (156624, 0.1369881430866801), (313431, 0.10698475713146899), (272143, 0.1042388584525598), (235827, 0.10113769184742637), (156447, 0.08783893363801018), (70646, 0.08409954033602747), (206934, 0.08146138019435344), (190559, 0.0801497244938313), (271551, 0.07922296987882174)]
[(199198, 0.2799747356368587), (272143, 0.27875614005188876), (175040, 0.2415397583322196), (336476, 0.18668836238506897), (182513, 0.12241980393274354), (284474, 0.08069039596278683), (348134, 0.07568701341748939), (156560, 0.07545421476168913), (233917, 0.06416618965038366), (315099, 0.054494597071643704)]
[(199198, 0.49483930091243444), (175040, 0.38986165472092865), (198659, 0.20908998133756568), (156560, 0.17969307321424893), (336476, 0.16407767766543774), (156624, 0.13490297352275948), (348111, 0.13190489146749043), (324823, 0.08504076711209806), (284474, 0.07075792228133822), (72256, 0.04290908864332235)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(272143, 0.18563655339343915), (156624, 0.1369881430866801), (182513, 0.12241980393274354), (336476, 0.11639602986490896), (156447, 0.08783893363801018), (284474, 0.08069039596278683), (348134, 0.07568701341748939), (64329, 0.07545421476168913), (157332, 0.0665280213300044), (166430, 0.06590535715208987)]
[(272143, 0.16715645005090363), (50864, 0.15074178380379075), (156624, 0.1369881430866801), (50383, 0.13514557010693226), (299767, 0.1289882580222607), (161160, 0.10840791429656242), (96481, 0.09112645567325996), (156447, 0.08783893363801018), (95743, 0.07951169611730846), (50619, 0.07762341432436974)]
[(160417, 0.2427110843391027), (156560, 0.22482707672469027), (162765, 0.1813363905861373), (160974, 0.159090992507536), (157332, 0.14044105998906584), (158229, 0.11101658048608612), (107039, 0.0972614455180946), (166283, 0.09179702964358943), (162655, 0.08967731152361727), (272143, 0.08526492529654099)]
[(64329, 0.4179510268801069), (175040, 0.33285043839602585), (336476, 0.2634451354836289), (182394, 0.26026963608834897), (348111, 0.20494603845902426), (156560, 0.16277583453331607), (324823, 0.14920713485641457), (199406, 0.1261637387030135), (182513, 0.12532747560114807), (30555, 0.12371007915228557)]
[(272143, 0.5423630865356845), (175040, 0.4260683003395364), (336476, 0.21583558819461882), (198659, 0.2062486145887856), (348111, 0.19057974635715916), (182394, 0.11014153830293937), (156624, 0.10896273921824375), (275192, 0.07775616900834297), (232753, 0.07585326888556977), (278808, 0.07585326888556977)]
[(175040, 0.5743901967282454), (198659, 0.37042249053350224), (336476, 0.21892647049036743), (348111, 0.19128704533525165), (156560, 0.17969307321424893), (156624, 0.13490297352275948), (182394, 0.11014153830293937), (324823, 0.08504076711209806), (284474, 0.07075792228133822), (224658, 0.06632827488421664)]
[(182513, 0.24996876218991318), (156624, 0.21412643215436256), (272143, 0.1980242035978375), (64329, 0.14574654728184916), (348111, 0.11639602986490896), (233917, 0.1148109975134215), (341838, 0.10715630398092232), (284474, 0.09069446284952913), (156447, 0.08783893363801018), (175040, 0.0825720650330476)]
[(162765, 0.1813363905861373), (161584, 0.17466544787793511), (156560, 0.1369881430866801), (156447, 0.1242218685419651), (158229, 0.11101658048608612), (158722, 0.09703182758590927), (157332, 0.08976206393186344), (159581, 0.08696386581798134), (272143, 0.08526492529654099), (160417, 0.08042054203791298)]
[(140450, 0.19732190434332983), (275190, 0.1894615908449756), (275189, 0.18307359666251405), (66171, 0.12479732999335877), (32486, 0.10938570047544141), (336476, 0.09069446284952913), (283327, 0.09016612023797267), (348111, 0.08069039596278683), (275192, 0.07775616900834297), (278808, 0.07585326888556977)]
[(272143, 0.4309452667962595), (199198, 0.4051211237764143), (336476, 0.23000268662089013), (156560, 0.21244235784836923), (162765, 0.1813363905861373), (156447, 0.1242218685419651), (158229, 0.11101658048608612), (348111, 0.10183573149867764), (157332, 0.08976206393186344), (160417, 0.08042054203791298)]
[(199198, 0.4051211237764143), (272143, 0.3456803414997185), (336476, 0.15286439755320763), (348111, 0.10183573149867764), (156560, 0.07545421476168913), (328760, 0.05581034781872852), (182513, 0.05468897749030404), (156624, 0.04963804822621849), (198659, 0.04491610539284904), (72256, 0.04290908864332235)]
[(160974, 0.14414482050765215), (299767, 0.1289882580222607), (158536, 0.11041310336685785), (351530, 0.095947639059033), (107205, 0.095947639059033), (206730, 0.095947639059033), (162655, 0.0938444249093069), (96481, 0.09112645567325996), (156624, 0.08042054203791298), (95743, 0.07951169611730846)]
[(182513, 0.31806159689146946), (348111, 0.1805622195152926), (119044, 0.11315185234737829), (273394, 0.11315185234737829), (206159, 0.11315185234737829), (69433, 0.11315185234737829), (206606, 0.11315185234737829), (161227, 0.11315185234737829), (161363, 0.11315185234737829), (237224, 0.11315185234737829)]
[(272143, 0.7013247555839347), (336476, 0.3241092202430462), (182513, 0.23434342232263938), (198659, 0.2062486145887856), (182394, 0.11014153830293937), (284474, 0.08069039596278683), (348134, 0.07568701341748939), (156560, 0.07545421476168913), (224658, 0.06632827488421664), (233917, 0.06416618965038366)]
[(156560, 0.19962763081681995), (162765, 0.1813363905861373), (160417, 0.17426496694721988), (158536, 0.16248940010147664), (272143, 0.1374808006652974), (157332, 0.13492106424276148), (156447, 0.1242218685419651), (158229, 0.11101658048608612), (160974, 0.0865198721131068), (336476, 0.07713828906768248)]
[(206934, 0.20088369924415383), (285218, 0.16618618571652527), (245045, 0.1441035441316245), (140548, 0.10753213940765202), (202576, 0.1072727216083059), (208322, 0.10261381518305736), (66236, 0.0930184377585412), (308512, 0.08564972372829179), (235230, 0.08409954033602747), (235440, 0.0794987981383073)]
[(97485, 0.20882320017436845), (272143, 0.16715645005090363), (97480, 0.1654884707784808), (96960, 0.15623548541982177), (156624, 0.1369881430866801), (299767, 0.1289882580222607), (95742, 0.11032564718565388), (91369, 0.09963398728176989), (96954, 0.09963398728176989), (96481, 0.09112645567325996)]
[(202557, -91), (162655, -92), (158536, -93), (199198, -94), (160417, -95), (16129, -96), (156624, -97), (300470, -98), (272143, -99), (160974, -100)]
[(202557, -91), (162655, -92), (158536, -93), (199198, -94), (160417, -95), (16129, -96), (156624, -97), (300470, -98), (272143, -99), (160974, -100)]
[(272143, 0.47160516425434634), (175040, 0.4260683003395364), (198659, 0.2062486145887856), (2303, 0.13931112187139225), (336476, 0.1251411253450897), (182394, 0.11014153830293937), (348111, 0.10988935039437231), (36161, 0.10310208986501465), (36129, 0.08028034417637815), (156560, 0.07545421476168913)]
[(156624, 0.1369881430866801), (199197, 0.13605473693350723), (272143, 0.1042388584525598), (289444, 0.10240991408261158), (13498, 0.10240991408261158), (156447, 0.08783893363801018), (96593, 0.0811579367615074), (129029, 0.07962688629227777), (128289, 0.07641975236777206), (64329, 0.07545421476168913)]
[(84371, 0.274889366287838), (137638, 0.1395276566378118), (284421, 0.13138171562999032), (58193, 0.12745898607466183), (236444, 0.11663498115960758), (236951, 0.11663498115960758), (205973, 0.11663498115960758), (286209, 0.11663498115960758), (293050, 0.11663498115960758), (140699, 0.11377990332835466)]
[(182513, 0.24996876218991318), (161584, 0.17466544787793511), (156624, 0.13465362955451093), (348111, 0.11639602986490896), (233917, 0.1148109975134215), (341838, 0.10715630398092232), (158722, 0.09703182758590927), (272143, 0.09378534514527773), (284474, 0.09069446284952913), (159581, 0.08696386581798134)]
[(272143, 0.2742467191433369), (64329, 0.2205925817690975), (175040, 0.1845285420073168), (303846, 0.18033688011112042), (166445, 0.17023830305046592), (198659, 0.16133250919593656), (187065, 0.1460490271720965), (129029, 0.13385712470511854), (313431, 0.13263587579461047), (95706, 0.12847458559243768)]
[(272143, 0.13361357030963575), (182513, 0.12241980393274354), (336476, 0.11639602986490896), (160417, 0.0938444249093069), (158536, 0.08967731152361727), (160974, 0.0865198721131068), (284474, 0.08069039596278683), (348134, 0.07568701341748939), (158082, 0.070905145249925), (233917, 0.06416618965038366)]
[(162765, 0.1813363905861373), (156560, 0.1369881430866801), (156447, 0.1242218685419651), (158229, 0.11101658048608612), (289444, 0.10240991408261158), (13498, 0.10240991408261158), (157332, 0.08976206393186344), (272143, 0.08526492529654099), (96593, 0.0811579367615074), (160417, 0.08042054203791298)]
[(272143, 0.29443613686849124), (47803, 0.22784770917926217), (64329, 0.2205925817690975), (175040, 0.19849878139825033), (198659, 0.16133250919593656), (182394, 0.131036541305807), (3246, 0.08864998989744582), (224658, 0.06632827488421664), (348111, 0.059382153867761245), (254489, 0.05850045843434677)]
[(25370, 0.5100697232983947), (160474, 0.36067376022224085), (29840, 0.17201904480216956), (208077, 0.05579752429068276), (107039, 0.05408026448576207), (156447, 0.026542112967397346), (199198, 0.014415422679994233), (156624, 0.013330885771572487), (272143, -99), (160974, -100)]
[(348111, 0.4009039247013187), (199198, 0.3314813600429287), (156624, 0.28230966007652913), (64329, 0.26765077763116946), (175040, 0.23089396142175667), (233917, 0.18290383221497777), (198659, 0.16417387594471664), (341838, 0.10715630398092232), (156560, 0.1042388584525598), (324823, 0.08504076711209806)]
[(199198, 0.4587752611506537), (64329, 0.43889820344322905), (336476, 0.17635741017832535), (198659, 0.16417387594471664), (348111, 0.13272622991294591), (324823, 0.12228561758866816), (156560, 0.1042388584525598), (156624, 0.08526492529654099), (284474, 0.07075792228133822), (328760, 0.05581034781872852)]
[(199198, 0.4416228983458681), (336476, 0.3437541073351909), (198659, 0.2481852529786437), (348111, 0.20381749887362288), (64329, 0.19735844511100942), (175040, 0.14832189638870905), (156624, 0.1458466800168214), (284474, 0.1280194618547869), (156560, 0.1042388584525598), (118864, 0.08881146774652446)]
[(285648, 0.18481089989236407), (160974, 0.14414482050765215), (336607, 0.11134994710096138), (158536, 0.11041310336685785), (162655, 0.0938444249093069), (156624, 0.08042054203791298), (260394, 0.07748470862188879), (292558, 0.07748470862188879), (245107, 0.07748470862188879), (172423, 0.07748470862188879)]
[(149599, 0.10344421877083577), (224857, 0.10306429718871057), (289444, 0.10240991408261158), (13498, 0.10240991408261158), (63736, 0.08517215530270575), (65831, 0.08517215530270575), (63688, 0.08517215530270575), (63683, 0.08517215530270575), (96593, 0.0811579367615074), (129029, 0.07962688629227777)]
[(285648, 0.18481089989236407), (336607, 0.11134994710096138), (3241, 0.10351298064743666), (286240, 0.10003290278428412), (312452, 0.10003290278428412), (313620, 0.08616365253045165), (135769, 0.08616365253045165), (272143, 0.08504076711209806), (260394, 0.07748470862188879), (292558, 0.07748470862188879)]
[(336476, 0.3437541073351909), (199198, 0.3314813600429287), (348111, 0.20381749887362288), (64329, 0.19735844511100942), (198659, 0.16417387594471664), (175040, 0.14832189638870905), (156624, 0.1458466800168214), (284474, 0.1280194618547869), (156560, 0.1042388584525598), (324823, 0.08504076711209806)]
[(161584, 0.17466544787793511), (159581, 0.08696386581798134), (157079, 0.07301493326732389), (50823, 0.07234646561530113), (283552, 0.0662345265724378), (141448, 0.059494792693202236), (140349, 0.059494792693202236), (156624, 0.05751534048682845), (160966, 0.05437361519926288), (160974, -100)]
[(343191, 0.4164701851078906), (135769, 0.35872789172491043), (199198, 0.2742467191433369), (141013, 0.2145454432166118), (146188, 0.2145454432166118), (64329, 0.19735844511100942), (198659, 0.16417387594471664), (175040, 0.14832189638870905), (297970, 0.14645004853840043), (187065, 0.1460490271720965)]
[(156447, 0.21206080217997528), (272143, 0.1895037837491008), (162765, 0.1813363905861373), (157332, 0.15629008526186783), (160417, 0.13985998309024417), (158229, 0.11101658048608612), (336476, 0.07713828906768248), (64329, 0.07545421476168913), (337890, 0.07324417494371821), (158536, 0.07281208857785937)]
[(175040, 0.2415397583322196), (199198, 0.2205925817690975), (272143, 0.19735844511100942), (205861, 0.11413135542638964), (207540, 0.09725505649044464), (351530, 0.095947639059033), (107205, 0.095947639059033), (206730, 0.095947639059033), (118726, 0.09438741086608106), (31960, 0.08637189285046422)]
[(156560, 0.2035161644166845), (162765, 0.1813363905861373), (160417, 0.14756288476069968), (156447, 0.1242218685419651), (158229, 0.11101658048608612), (272143, 0.08526492529654099), (336476, 0.07713828906768248), (337890, 0.07324417494371821), (158536, 0.07281208857785937), (273054, 0.07241474470854635)]
[(224857, 0.44302765568359714), (292708, 0.15610473950771406), (70673, 0.12371007915228557), (237055, 0.12371007915228557), (342917, 0.11038271988126416), (223931, 0.09012711337655513), (166430, 0.07913401120276446), (330745, 0.06896974169838807), (166445, 0.06152132588197724), (160974, -100)]
[(336476, 0.3202610947100732), (199198, 0.27782722266868926), (175040, 0.2415397583322196), (336801, 0.21308562285528926), (272143, 0.19735844511100942), (145329, 0.19278823416444013), (348111, 0.1729270004593546), (195586, 0.17201904480216956), (337746, 0.1575702223826808), (62675, 0.14630719950826976)]
[(107301, 0.1786889993417549), (156560, 0.13243337848209427), (164013, 0.11038271988126416), (207469, 0.09464216817386983), (156624, 0.08976206393186344), (224171, 0.07913401120276446), (341092, 0.07805236975385703), (236897, 0.07805236975385703), (286418, 0.07805236975385703), (50823, 0.07718967948100029)]
[(272143, 0.43842059508805353), (64329, 0.2205925817690975), (182394, 0.1941529153368664), (175040, 0.1845285420073168), (13811, 0.11211930324396888), (118753, 0.07767529402182977), (7694, 0.07431102627934141), (169111, 0.07022648096771238), (224658, 0.06632827488421664), (324823, 0.06416636774431653)]
[(292708, 0.15610473950771406), (70673, 0.12371007915228557), (237055, 0.12371007915228557), (225514, 0.11038271988126416), (342917, 0.11038271988126416), (24764, 0.10425809785606158), (223931, 0.09012711337655513), (166430, 0.07913401120276446), (70036, 0.07689590405005342), (224857, 0.071424047500042)]
[(289444, 0.10240991408261158), (13498, 0.10240991408261158), (351530, 0.095947639059033), (107205, 0.095947639059033), (206730, 0.095947639059033), (96593, 0.0811579367615074), (129029, 0.07962688629227777), (128289, 0.07641975236777206), (331226, 0.07603670497064792), (321118, 0.07603670497064792)]
[(199198, 0.2742467191433369), (156624, 0.23254232971523286), (64329, 0.19735844511100942), (161584, 0.17466544787793511), (156560, 0.17076687978256422), (198659, 0.16417387594471664), (175040, 0.14832189638870905), (158722, 0.09703182758590927), (336476, 0.09378534514527773), (159581, 0.08696386581798134)]
[(64329, 0.4179510268801069), (175040, 0.33285043839602585), (198659, 0.3255063851406532), (336476, 0.26503016783511635), (182513, 0.17965444483233534), (284474, 0.15144831824412505), (182394, 0.11014153830293937), (156560, 0.1042388584525598), (156624, 0.08526492529654099), (324823, 0.08504076711209806)]
[(199198, 0.2742467191433369), (64329, 0.19735844511100942), (198659, 0.16417387594471664), (175040, 0.14832189638870905), (199197, 0.11110277035639192), (313431, 0.10698475713146899), (156560, 0.1042388584525598), (235827, 0.10113769184742637), (336476, 0.09378534514527773), (156624, 0.08526492529654099)]
[(160974, 0.30583952747631377), (158536, 0.13526598385274985), (160417, 0.1317121295064283), (162655, 0.11316314876953734), (161858, 0.061212749824087684), (236802, 0.05100697232983947), (210994, 0.05100697232983947), (283835, 0.05100697232983947), (16129, 0.045616040769757886), (31632, 0.04551196133134187)]
[(165815, 0.35872789172491043), (87188, 0.21500126266628747), (156624, 0.1369881430866801), (272143, 0.1042388584525598), (156447, 0.08783893363801018), (87207, 0.07828084370101546), (64329, 0.07545421476168913), (157332, 0.0665280213300044), (166430, 0.06590535715208987), (162655, 0.06263948773013987)]
[(272143, 0.47160516425434634), (175040, 0.4260683003395364), (336476, 0.37510988753500285), (198659, 0.29025999162271265), (348111, 0.23230915432711585), (224658, 0.13244499563569917), (156624, 0.11021980294649891), (118864, 0.08881146774652446), (156560, 0.07545421476168913), (233917, 0.06809283470155628)]
[(283123, 0.46368536068055277), (128419, 0.17851259917722495), (282539, 0.17851259917722495), (226101, 0.06660560348705334), (215839, 0.06660560348705334), (215770, 0.06660560348705334), (285343, 0.05696403594023164), (195839, 0.05472724952939048), (201768, 0.0489495400677242), (160974, -100)]
[(156560, 0.2629556054690157), (158536, 0.1832251919447172), (162765, 0.1813363905861373), (160974, 0.14414482050765215), (156447, 0.1242218685419651), (158229, 0.11101658048608612), (162655, 0.0938444249093069), (272143, 0.08526492529654099), (336476, 0.07713828906768248), (337890, 0.07324417494371821)]

 58%|█████▊    | 4452/7721 [00:00<00:00, 4251.83it/s]

[(300470, 0.3557336559267564), (162300, 0.34983727127076203), (16129, 0.24817664391348115), (158082, 0.22298036956472989), (162655, 0.1835217364329242), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (166283, 0.15950322319103769), (156624, 0.15323263061577236), (59758, 0.12538033733281437)]
[(16129, 0.29379268468323905), (300470, 0.28150993575629535), (158536, 0.23200224543083808), (225463, 0.21517513748450606), (202557, 0.21353050149075908), (160417, 0.20522062503176436), (158082, 0.14279213587890255), (156808, 0.1337101516848802), (59758, 0.12538033733281437), (162655, 0.042258003519612335)]
[(300470, 0.38158051432023743), (16129, 0.335051303128969), (225463, 0.225518480077774), (162300, 0.21585021382334774), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (225055, 0.04695771949396283)]
[(300470, 0.3236956808813002), (225463, 0.28012244980836687), (162300, 0.26146625459310563), (202557, 0.26023809814653576), (59758, 0.2008029870401418), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.07949171330613487)]
[(313061, 0.3550495329769162), (16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (274915, 0.2082350925539453), (331187, 0.1946190556814265), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (68887, 0.15109311015596852)]
[(300470, 0.30295703974562765), (162300, 0.2887614667466498), (160417, 0.25455792387451), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.1523440445824138), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (166283, 0.09179702964358943)]
[(300470, 0.30295703974562765), (162300, 0.2887614667466498), (160417, 0.25455792387451), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.1523440445824138), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (166283, 0.09179702964358943)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(160974, 0.3599950343309999), (158536, 0.18332435629015995), (162655, 0.13610242842891923), (158082, 0.12343914720825261), (300470, 0.0931684003501095), (156624, 0.08042054203791298), (166283, 0.06770619354744825), (157332, 0.0671423427227867), (156560, 0.0594394410523312), (16129, 0.045616040769757886)]
[(16129, 0.4176288324229547), (225463, 0.33310014714445485), (158536, 0.22092988066584912), (162300, 0.21585021382334774), (160417, 0.19692143668878087), (59758, 0.19455166137344698), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (272660, 0.07848293595695409), (298310, 0.05896453910899386)]
[(79015, 0.3222253204769533), (83472, 0.29669934630327804), (84741, 0.22784770917926217), (83646, 0.14834967315163902), (83622, 0.13268798144277613), (84916, 0.08228959280716278), (162655, 0.012936706265711879), (199198, 0.012878713965800303), (272143, 0.010277391614076491), (160974, -100)]
[(300470, 0.29389476776844325), (162300, 0.27692601834745995), (158536, 0.26950409587439383), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.16062563863528212), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (162655, 0.0938444249093069)]
[(272143, 0.4906364704568099), (160974, 0.3828986052814438), (272660, 0.23605793732990915), (300470, 0.2324454165776628), (64329, 0.2205925817690975), (15152, 0.20711164485320396), (16129, 0.20530376676880818), (175040, 0.1845285420073168), (14229, 0.1604279902644168), (16911, 0.1355863985495169)]
[(96165, 0.25503486164919736), (97600, 0.22617838299626358), (96481, 0.19732190434332983), (119592, 0.19732190434332983), (97458, 0.15533373363990297), (273464, 0.1395276566378118), (96166, 0.1337885247242297), (363291, 0.12847458559243768), (95756, 0.11392385458963109), (118683, 0.11377990332835466)]
[(160974, 0.3852629720949667), (158536, 0.17225199152517098), (162655, 0.14953685037965625), (202557, 0.14046236273292292), (225463, 0.10758166706668083), (16129, 0.08257752929398565), (156624, 0.08042054203791298), (272660, 0.07848293595695409), (158082, 0.0706363249823161), (59758, 0.06917132404063263)]
[(16129, 0.29379268468323905), (300470, 0.28150993575629535), (158536, 0.23200224543083808), (225463, 0.21517513748450606), (202557, 0.21353050149075908), (160417, 0.20522062503176436), (158082, 0.14279213587890255), (156808, 0.1337101516848802), (59758, 0.12538033733281437), (162655, 0.042258003519612335)]
[(300470, 0.31960108754426864), (16129, 0.3076991789277927), (59758, 0.2534508587149606), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (284844, 0.11097671047150096), (313504, 0.10798741594776293)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (155023, 0.09734545040003979), (158082, 0.08998931365296603)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(160974, 0.24817664391348115), (15226, 0.20711164485320396), (14229, 0.1604279902644168), (16911, 0.1355863985495169), (225463, 0.1091240539728442), (202557, 0.08687465921548786), (300470, 0.08257752929398565), (96812, 0.07949171330613487), (260931, 0.07576702839157815), (59758, 0.07542264970732743)]
[(202557, -91), (162655, -92), (158536, -93), (199198, -94), (160417, -95), (16129, -96), (156624, -97), (300470, -98), (272143, -99), (160974, -100)]
[(225463, 0.3463320702125249), (300470, 0.3236956808813002), (162300, 0.26146625459310563), (202557, 0.26023809814653576), (59758, 0.2008029870401418), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (260931, 0.07576702839157815)]
[(160974, 0.4892947955007957), (202557, 0.22733702194841077), (225463, 0.21670572103952504), (59758, 0.14459397374796007), (272660, 0.13800547097126564), (96812, 0.07949171330613487), (260931, 0.07576702839157815), (158536, 0.061838888158313135), (298310, 0.05896453910899386), (162655, 0.05569242547034934)]
[(16129, 0.3307541732074668), (202557, 0.3138258016639708), (225463, 0.2785800629022035), (158536, 0.22092988066584912), (162300, 0.21585021382334774), (160417, 0.19692143668878087), (59758, 0.19455166137344698), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (272660, 0.07848293595695409)]
[(300470, 0.3236956808813002), (225463, 0.28012244980836687), (162300, 0.26146625459310563), (202557, 0.26023809814653576), (59758, 0.2008029870401418), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.07949171330613487)]
[(160974, 0.14414482050765215), (158536, 0.11041310336685785), (162655, 0.0938444249093069), (156624, 0.08042054203791298), (158082, 0.0706363249823161), (166283, 0.06770619354744825), (157332, 0.0671423427227867), (162300, 0.06107580452411221), (156560, 0.0594394410523312), (300470, 0.05277661618112871)]
[(160974, 0.1978019980898793), (16129, 0.1549143630134623), (225463, 0.1291689875166315), (272660, 0.12807052138214622), (300470, 0.06917132404063263), (271848, 0.06207780001234846), (284312, 0.05054289552980496), (186042, 0.04919549257341982), (337540, 0.047376344609021646), (284622, 0.046671226964622066)]
[(270847, 0.4592467895639849), (272314, 0.4317643757656486), (16129, 0.3307541732074668), (202557, 0.3138258016639708), (225463, 0.2785800629022035), (158536, 0.22092988066584912), (162300, 0.21585021382334774), (271558, 0.20353567865244448), (160417, 0.19692143668878087), (59758, 0.19455166137344698)]
[(300470, 0.30295703974562765), (162300, 0.2887614667466498), (160417, 0.25455792387451), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.1523440445824138), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (166283, 0.09179702964358943)]
[(16129, 0.29379268468323905), (300470, 0.28150993575629535), (158536, 0.23200224543083808), (225463, 0.21517513748450606), (202557, 0.21353050149075908), (160417, 0.20522062503176436), (158082, 0.14279213587890255), (156808, 0.1337101516848802), (59758, 0.12538033733281437), (162655, 0.042258003519612335)]
[(284312, 0.17253766289901798), (285023, 0.07826243580495225), (293425, 0.07362222301295154), (284629, 0.06851847711140549), (160974, 0.06709833887801207), (70023, 0.05696192729481554), (145349, 0.05244952993616594), (183675, 0.04908148200863436), (182163, 0.04908148200863436), (307195, 0.04908148200863436)]
[(160974, 0.08998931365296603), (162655, 0.070905145249925), (160417, 0.0706363249823161), (158536, 0.06235473092944776), (161858, 0.061212749824087684), (162300, 0.05280282222593651), (236802, 0.05100697232983947), (210994, 0.05100697232983947), (283835, 0.05100697232983947), (31632, 0.04551196133134187)]
[(160974, 0.48110672922227166), (59758, 0.19724184542277884), (160417, 0.16318971954798656), (162655, 0.1453697369939666), (16129, 0.14210006430829722), (202557, 0.14046236273292292), (284844, 0.11097671047150096), (313504, 0.10798741594776293), (225463, 0.10758166706668083), (166283, 0.09179702964358943)]
[(202557, -91), (162655, -92), (158536, -93), (199198, -94), (160417, -95), (16129, -96), (156624, -97), (300470, -98), (272143, -99), (160974, -100)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(160974, 0.42154008284452904), (300470, 0.22303989202690858), (225463, 0.16364413821509555), (96812, 0.07949171330613487), (260931, 0.07576702839157815), (59758, 0.07542264970732743), (272660, 0.05952253501431156), (225055, 0.04695771949396283), (202428, 0.04656258378954941), (162300, 0.045616040769757886)]
[(162300, 0.34983727127076203), (16129, 0.3307541732074668), (202557, 0.3138258016639708), (225463, 0.2785800629022035), (162655, 0.23921416190327352), (158082, 0.22298036956472989), (59758, 0.19455166137344698), (166283, 0.15950322319103769), (128988, 0.15845231093012707), (156624, 0.15323263061577236)]
[(300470, 0.3236956808813002), (225463, 0.28012244980836687), (162300, 0.26146625459310563), (202557, 0.26023809814653576), (59758, 0.2008029870401418), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.07949171330613487)]
[(300470, 0.30295703974562765), (162300, 0.2887614667466498), (160417, 0.25455792387451), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.1523440445824138), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (166283, 0.09179702964358943)]
[(107136, 0.2744474531076814), (283042, 0.19406365517181853), (50568, 0.1324690531448756), (282785, 0.1255704854884302), (224075, 0.09148248436922714), (160974, 0.08998931365296603), (283026, 0.0822051792575836), (162655, 0.070905145249925), (160417, 0.0706363249823161), (158536, 0.06235473092944776)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(87126, 0.35214421872181506), (165815, 0.3079137036104202), (87173, 0.25277422669251604), (106819, 0.25245493881090375), (85318, 0.21500126266628747), (60258, 0.1986304836445498), (87165, 0.19557283838508044), (87234, 0.18489063377581955), (160974, 0.159090992507536), (87193, 0.1113063388914321)]
[(96672, 0.45518577118939274), (16129, 0.3307541732074668), (202557, 0.3138258016639708), (95742, 0.2803488882851188), (225463, 0.2785800629022035), (158536, 0.22092988066584912), (162300, 0.21585021382334774), (97485, 0.20882320017436845), (95930, 0.2030620238896006), (160417, 0.19692143668878087)]
[(160974, 0.30323581301518815), (162655, 0.1835217364329242), (166283, 0.15950322319103769), (156624, 0.15323263061577236), (162300, 0.1339870574474143), (158082, 0.13299105591176386), (300470, 0.11461550433944184), (161858, 0.0706541780456455), (157332, 0.0671423427227867), (156560, 0.0594394410523312)]
[(300470, 0.3236956808813002), (225463, 0.28012244980836687), (162300, 0.26146625459310563), (202557, 0.26023809814653576), (59758, 0.2008029870401418), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.07949171330613487)]
[(16129, 0.3307541732074668), (202557, 0.3138258016639708), (225463, 0.2785800629022035), (158536, 0.22092988066584912), (162300, 0.21585021382334774), (160417, 0.19692143668878087), (59758, 0.19455166137344698), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (272660, 0.07848293595695409)]
[(16129, 0.29379268468323905), (300470, 0.28150993575629535), (158536, 0.23200224543083808), (225463, 0.21517513748450606), (202557, 0.21353050149075908), (160417, 0.20522062503176436), (158082, 0.14279213587890255), (156808, 0.1337101516848802), (59758, 0.12538033733281437), (162655, 0.042258003519612335)]
[(129364, 0.15845231093012707), (218144, 0.13882339503596355), (59758, 0.12807052138214622), (284844, 0.11097671047150096), (313504, 0.10798741594776293), (264825, 0.10753213940765202), (160974, 0.08089758512742111), (300470, 0.07848293595695409), (236613, 0.06089593473724781), (16129, 0.05952253501431156)]
[(300470, 0.38158051432023743), (16129, 0.335051303128969), (225463, 0.225518480077774), (162300, 0.21585021382334774), (158536, 0.159090992507536), (160417, 0.14414482050765215), (225201, 0.1316994362492872), (59758, 0.12538033733281437), (187067, 0.095947639059033), (156808, 0.09421911878204836)]
[(16129, 0.3307541732074668), (202557, 0.3138258016639708), (225463, 0.2785800629022035), (158536, 0.22092988066584912), (162300, 0.21585021382334774), (160417, 0.19692143668878087), (59758, 0.19455166137344698), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (272660, 0.07848293595695409)]
[(166215, 0.2147864250446643), (274915, 0.2082350925539453), (212196, 0.16414788498337793), (68887, 0.15109311015596852), (119044, 0.15086301289705312), (273394, 0.15086301289705312), (206159, 0.15086301289705312), (2303, 0.13931112187139225), (331242, 0.12022458674074694), (118500, 0.11742126555152319)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(16129, 0.29379268468323905), (300470, 0.28150993575629535), (158536, 0.23200224543083808), (225463, 0.21517513748450606), (202557, 0.21353050149075908), (160417, 0.20522062503176436), (158082, 0.14279213587890255), (156808, 0.1337101516848802), (59758, 0.12538033733281437), (162655, 0.042258003519612335)]
[(300470, 0.3236956808813002), (225463, 0.28012244980836687), (162300, 0.26146625459310563), (202557, 0.26023809814653576), (59758, 0.2008029870401418), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.07949171330613487)]
[(160974, 0.4544545663737166), (300470, 0.2302317892915724), (225463, 0.1720834210853177), (284844, 0.11097671047150096), (313504, 0.10798741594776293), (202557, 0.08687465921548786), (96812, 0.07949171330613487), (260931, 0.07576702839157815), (271848, 0.06207780001234846), (236613, 0.06089593473724781)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(300470, 0.38158051432023743), (16129, 0.335051303128969), (225463, 0.225518480077774), (162300, 0.21585021382334774), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (225055, 0.04695771949396283)]
[(300470, 0.3236956808813002), (225463, 0.28012244980836687), (162300, 0.26146625459310563), (202557, 0.26023809814653576), (59758, 0.2008029870401418), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.07949171330613487)]
[(300470, 0.38158051432023743), (16129, 0.335051303128969), (225463, 0.225518480077774), (162300, 0.21585021382334774), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (225055, 0.04695771949396283)]
[(160974, 0.32201573671473566), (59758, 0.19724184542277884), (16129, 0.14210006430829722), (202557, 0.14046236273292292), (284844, 0.11097671047150096), (313504, 0.10798741594776293), (225463, 0.10758166706668083), (158536, 0.061838888158313135), (236613, 0.06089593473724781), (298310, 0.05896453910899386)]
[(16129, 0.3307541732074668), (202557, 0.3138258016639708), (225463, 0.2785800629022035), (158536, 0.22092988066584912), (162300, 0.21585021382334774), (160417, 0.19692143668878087), (59758, 0.19455166137344698), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (272660, 0.07848293595695409)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (284629, 0.18602985597108745), (59758, 0.17592323286261932), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836)]
[(160974, 0.159090992507536), (2303, 0.13931112187139225), (160417, 0.11041310336685785), (36161, 0.10310208986501465), (166283, 0.09179702964358943), (162655, 0.08967731152361727), (36129, 0.08028034417637815), (162300, 0.0729112529233021), (156624, 0.07281208857785937), (161858, 0.0706541780456455)]
[(165815, 0.5310551967858137), (87207, 0.4223701825217527), (87126, 0.26126297358137796), (106819, 0.25245493881090375), (87173, 0.14146788780108396), (87191, 0.12185380599216758), (87165, 0.10945449905878096), (160974, 0.08998931365296603), (162655, 0.070905145249925), (160417, 0.0706363249823161)]
[(300470, 0.42197229848921824), (16129, 0.3806673438987269), (225463, 0.2696952217267574), (158536, 0.23200224543083808), (160417, 0.20522062503176436), (284312, 0.17253766289901798), (158082, 0.14279213587890255), (156808, 0.1337101516848802), (59758, 0.12538033733281437), (285023, 0.07826243580495225)]

 70%|██████▉   | 5377/7721 [00:01<00:00, 4268.35it/s]

[(160974, 0.3852629720949667), (158536, 0.17225199152517098), (162655, 0.14953685037965625), (202557, 0.14046236273292292), (225463, 0.10758166706668083), (16129, 0.08257752929398565), (156624, 0.08042054203791298), (272660, 0.07848293595695409), (158082, 0.0706363249823161), (59758, 0.06917132404063263)]
[(129086, 0.2637320450404263), (160974, 0.24111815158731453), (78346, 0.19648335830400424), (129687, 0.17649007662455862), (84493, 0.17649007662455862), (141655, 0.15207340994129584), (141517, 0.15207340994129584), (129308, 0.14392145858854952), (202557, 0.14046236273292292), (129238, 0.13893471504706753)]
[(105121, 0.17129944745658357), (161169, 0.1093638945573481), (119044, 0.07543456823158552), (273394, 0.07543456823158552), (206159, 0.07543456823158552), (69433, 0.07543456823158552), (206606, 0.07543456823158552), (161227, 0.07543456823158552), (161363, 0.07543456823158552), (160974, -100)]
[(16129, 0.4176288324229547), (225463, 0.33310014714445485), (158536, 0.22092988066584912), (162300, 0.21585021382334774), (160417, 0.19692143668878087), (59758, 0.19455166137344698), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (272660, 0.07848293595695409), (284666, 0.07340855824438847)]
[(59758, 0.12807052138214622), (284844, 0.11097671047150096), (313504, 0.10798741594776293), (160974, 0.08089758512742111), (300470, 0.07848293595695409), (236613, 0.06089593473724781), (16129, 0.05952253501431156), (273464, 0.05853490036423154), (10034, 0.05448325533842525), (336429, 0.050821381239274696)]
[(202557, 0.4408675234391699), (225463, 0.4318808585240311), (158536, 0.2938411335891512), (59758, 0.2699743110807744), (160417, 0.2579972412128931), (158082, 0.14279213587890255), (272660, 0.13800547097126564), (156808, 0.1337101516848802), (162655, 0.09795042898996167), (96812, 0.07949171330613487)]
[(68887, 0.12007662799870396), (160417, 0.0938444249093069), (158536, 0.08967731152361727), (160974, 0.0865198721131068), (273395, 0.08336531941596413), (209294, 0.0759431276457301), (158082, 0.070905145249925), (159762, 0.06806749827108248), (156560, 0.06263948773013987), (293301, 0.05894818267481078)]
[(162300, 0.26865303604928426), (16129, 0.24817664391348115), (300470, 0.24111815158731453), (158536, 0.22144572343698377), (160417, 0.21478114548996824), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (162655, 0.070905145249925)]
[(300470, 0.3236956808813002), (225463, 0.28012244980836687), (162300, 0.26146625459310563), (202557, 0.26023809814653576), (59758, 0.2008029870401418), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.07949171330613487)]
[(300470, 0.38158051432023743), (16129, 0.335051303128969), (225463, 0.225518480077774), (162300, 0.21585021382334774), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (225055, 0.04695771949396283)]
[(32446, 0.20882320017436845), (33497, 0.20882320017436845), (160974, 0.17099839583552265), (202528, 0.14575492688072578), (316458, 0.12056413083371074), (83792, 0.11550804670065219), (16129, 0.1091240539728442), (300470, 0.10758166706668083), (31349, 0.09963398728176989), (284901, 0.09745173021303453)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(16129, 0.29379268468323905), (300470, 0.28150993575629535), (158536, 0.23200224543083808), (225463, 0.21517513748450606), (202557, 0.21353050149075908), (160417, 0.20522062503176436), (158082, 0.14279213587890255), (156808, 0.1337101516848802), (59758, 0.12538033733281437), (162655, 0.042258003519612335)]
[(160974, 0.24111815158731453), (272660, 0.186470351904717), (202557, 0.14046236273292292), (87203, 0.11162212531024944), (225463, 0.10758166706668083), (255486, 0.10201394465967895), (236613, 0.09928299052707186), (319880, 0.08340647828484926), (320720, 0.08340647828484926), (321723, 0.08340647828484926)]
[(162300, 0.26865303604928426), (16129, 0.24817664391348115), (300470, 0.24111815158731453), (158536, 0.22144572343698377), (160417, 0.21478114548996824), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (162655, 0.070905145249925)]
[(300470, 0.3557336559267564), (162300, 0.34983727127076203), (16129, 0.24817664391348115), (158082, 0.22298036956472989), (162655, 0.1835217364329242), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (166283, 0.15950322319103769), (156624, 0.15323263061577236), (59758, 0.12538033733281437)]
[(300470, 0.30295703974562765), (162300, 0.2887614667466498), (160417, 0.25455792387451), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.1523440445824138), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (166283, 0.09179702964358943)]
[(300470, 0.3557336559267564), (162300, 0.34983727127076203), (58096, 0.320075158221286), (16129, 0.24817664391348115), (58337, 0.22755980665670933), (162655, 0.22750283659558462), (158082, 0.22298036956472989), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (58643, 0.16129820911147802)]
[(158536, 0.25088802215112543), (16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (160417, 0.2118510140551004), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(160974, 0.21585021382334774), (162286, 0.2082350925539453), (353713, 0.10489905987233188), (352614, 0.10489905987233188), (158536, 0.09693742335741609), (162655, 0.08207218481528822), (121359, 0.0761393493311279), (271276, 0.07347325737593872), (160417, 0.06107580452411221), (158461, 0.05671985990404927)]
[(300470, 0.3236956808813002), (225463, 0.28012244980836687), (162300, 0.26146625459310563), (202557, 0.26023809814653576), (59758, 0.2008029870401418), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.07949171330613487)]
[(16129, 0.3307541732074668), (202557, 0.3138258016639708), (225463, 0.2785800629022035), (158536, 0.22092988066584912), (162300, 0.21585021382334774), (160417, 0.19692143668878087), (59758, 0.19455166137344698), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (272660, 0.07848293595695409)]
[(162300, 0.34156428897258634), (160417, 0.3251942488568261), (300470, 0.30295703974562765), (16129, 0.24817664391348115), (136075, 0.2145454432166118), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (162655, 0.16058245677354227), (161858, 0.1318669278697332), (59758, 0.12538033733281437)]
[(300470, 0.3236956808813002), (162300, 0.31426907681904215), (225463, 0.28012244980836687), (202557, 0.26023809814653576), (158536, 0.22144572343698377), (160417, 0.21478114548996824), (59758, 0.2008029870401418), (156808, 0.09421911878204836), (96812, 0.07949171330613487), (260931, 0.07576702839157815)]
[(160974, 0.40020914409485053), (166215, 0.2147864250446643), (166142, 0.17273606344008116), (212196, 0.16414788498337793), (348132, 0.16339806034941412), (160417, 0.16318971954798656), (50823, 0.15074178380379075), (162655, 0.1453697369939666), (313061, 0.1441035441316245), (202557, 0.14046236273292292)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(160974, 0.2456108646206428), (160417, 0.20425752827616475), (158082, 0.13325987617937277), (156624, 0.12312661327811347), (300470, 0.11753131362866248), (166283, 0.09179702964358943), (162300, 0.0729112529233021), (161858, 0.0706541780456455), (156560, 0.06263948773013987), (272143, 0.052215875368756395)]
[(300470, 0.3236956808813002), (225463, 0.28012244980836687), (162300, 0.26146625459310563), (202557, 0.26023809814653576), (59758, 0.2008029870401418), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.07949171330613487)]
[(300470, 0.30295703974562765), (162300, 0.2887614667466498), (160417, 0.25455792387451), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.1523440445824138), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (166283, 0.09179702964358943)]
[(16129, 0.3307541732074668), (202557, 0.3138258016639708), (225463, 0.2785800629022035), (158536, 0.22092988066584912), (162300, 0.21585021382334774), (160417, 0.19692143668878087), (59758, 0.19455166137344698), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (272660, 0.07848293595695409)]
[(160974, 0.29530243726872407), (202557, 0.14046236273292292), (158536, 0.13249306620395862), (225463, 0.10758166706668083), (16129, 0.08257752929398565), (272660, 0.07848293595695409), (166393, 0.07174557834498207), (59758, 0.06917132404063263), (48731, 0.06444506409539065), (158082, 0.061212749824087684)]
[(300470, 0.49910122908593296), (16129, 0.3806673438987269), (160417, 0.3156337283986222), (96256, 0.300566450599233), (225463, 0.2696952217267574), (256854, 0.24044917348149392), (172096, 0.24044917348149392), (95930, 0.21882291446196295), (97480, 0.2174944607970515), (158082, 0.20514686680835031)]
[(16129, 0.3307541732074668), (202557, 0.3138258016639708), (225463, 0.2785800629022035), (158536, 0.22092988066584912), (162300, 0.21585021382334774), (160417, 0.19692143668878087), (59758, 0.19455166137344698), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (272660, 0.07848293595695409)]
[(272660, 0.23605793732990915), (160974, 0.12538033733281437), (87203, 0.11162212531024944), (255486, 0.10201394465967895), (236613, 0.09928299052707186), (319880, 0.08340647828484926), (320720, 0.08340647828484926), (321723, 0.08340647828484926), (114461, 0.08048592087636894), (16129, 0.07542264970732743)]
[(87693, 0.2790553132756236), (58096, 0.23811877229846257), (57850, 0.21967507280760062), (59431, 0.21967507280760062), (58784, 0.19732190434332983), (59034, 0.19732190434332983), (59704, 0.19732190434332983), (59499, 0.18033688011112042), (59673, 0.1472444460259031), (59310, 0.11801902116367535)]
[(160974, 0.1978019980898793), (16129, 0.1549143630134623), (225463, 0.1291689875166315), (272660, 0.12807052138214622), (300470, 0.06917132404063263), (271848, 0.06207780001234846), (284312, 0.05054289552980496), (186042, 0.04919549257341982), (337540, 0.047376344609021646), (284622, 0.046671226964622066)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(16129, 0.3307541732074668), (202557, 0.3138258016639708), (225463, 0.2785800629022035), (158536, 0.22092988066584912), (162300, 0.21585021382334774), (160417, 0.19692143668878087), (59758, 0.19455166137344698), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (272660, 0.07848293595695409)]
[(16129, 0.29379268468323905), (300470, 0.28150993575629535), (158536, 0.23200224543083808), (225463, 0.21517513748450606), (202557, 0.21353050149075908), (160417, 0.20522062503176436), (158082, 0.14279213587890255), (156808, 0.1337101516848802), (59758, 0.12538033733281437), (162655, 0.042258003519612335)]
[(16129, 0.3307541732074668), (202557, 0.3138258016639708), (225463, 0.2785800629022035), (158536, 0.22092988066584912), (162300, 0.21585021382334774), (160417, 0.19692143668878087), (59758, 0.19455166137344698), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (272660, 0.07848293595695409)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(160974, 0.4121165474228372), (202557, 0.19498244697517428), (16129, 0.19170158326682984), (59758, 0.13213069115310613), (272660, 0.07848293595695409), (96812, 0.066209620404158), (158536, 0.061838888158313135), (298310, 0.05896453910899386), (162655, 0.05569242547034934), (199197, 0.05401276093646443)]
[(160974, 0.2380967347135347), (284312, 0.17253766289901798), (16129, 0.1091240539728442), (300470, 0.10758166706668083), (285023, 0.07826243580495225), (293425, 0.07362222301295154), (284629, 0.06851847711140549), (96812, 0.066209620404158), (59758, 0.0629593671124735), (70023, 0.05696192729481554)]
[(300470, 0.38158051432023743), (16129, 0.335051303128969), (225463, 0.225518480077774), (162300, 0.21585021382334774), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (225055, 0.04695771949396283)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(160974, 0.1846111496861299), (156025, 0.17427838412265004), (157077, 0.14392145858854952), (16129, 0.11919732537075112), (300470, 0.10758166706668083), (161178, 0.09614217107901918), (96812, 0.066209620404158), (59758, 0.0629593671124735), (160894, 0.06011229337037348), (202557, 0.054520084242251354)]
[(160974, 0.4892947955007957), (202557, 0.22733702194841077), (225463, 0.21670572103952504), (59758, 0.14459397374796007), (272660, 0.13800547097126564), (96812, 0.07949171330613487), (260931, 0.07576702839157815), (158536, 0.061838888158313135), (298310, 0.05896453910899386), (162655, 0.05569242547034934)]
[(160974, 0.37494120633088374), (160417, 0.17148890789097004), (162655, 0.1319353150432296), (158082, 0.11515755315538427), (300470, 0.10223067232729392), (166283, 0.09179702964358943), (156624, 0.07281208857785937), (161858, 0.0706541780456455), (160894, 0.04698826356216995), (16129, 0.045616040769757886)]
[(355997, 0.37160360818355515), (300470, 0.358649465215977), (160417, 0.34840234878381693), (129960, 0.2944888920518062), (162300, 0.2887614667466498), (158082, 0.28446193965642647), (199198, 0.2742467191433369), (16129, 0.24817664391348115), (141013, 0.2145454432166118), (146188, 0.2145454432166118)]
[(16129, 0.3307541732074668), (202557, 0.3138258016639708), (225463, 0.2785800629022035), (158536, 0.22092988066584912), (162300, 0.21585021382334774), (160417, 0.19692143668878087), (59758, 0.19455166137344698), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (272660, 0.07848293595695409)]
[(16129, 0.3235992936208086), (300470, 0.3102894756279472), (225463, 0.23395776294799614), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (158536, 0.159090992507536), (160417, 0.14414482050765215), (272660, 0.12807052138214622), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(160974, 0.14414482050765215), (158536, 0.11041310336685785), (162655, 0.0938444249093069), (156624, 0.08042054203791298), (158082, 0.0706363249823161), (166283, 0.06770619354744825), (157332, 0.0671423427227867), (162300, 0.06107580452411221), (156560, 0.0594394410523312), (300470, 0.05277661618112871)]
[(160974, 0.3852629720949667), (158536, 0.17225199152517098), (162655, 0.14953685037965625), (202557, 0.14046236273292292), (225463, 0.10758166706668083), (16129, 0.08257752929398565), (156624, 0.08042054203791298), (272660, 0.07848293595695409), (158082, 0.0706363249823161), (59758, 0.06917132404063263)]
[(160974, 0.24817664391348115), (225463, 0.1091240539728442), (202557, 0.08687465921548786), (300470, 0.08257752929398565), (96812, 0.07949171330613487), (260931, 0.07576702839157815), (59758, 0.07542264970732743), (272660, 0.05952253501431156), (162300, 0.045616040769757886), (15152, 0.04151412617727313)]
[(300470, 0.29389476776844325), (162300, 0.27692601834745995), (158536, 0.26950409587439383), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.16062563863528212), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (162655, 0.0938444249093069)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(300470, 0.44564362110306155), (225463, 0.3430818169208404), (162300, 0.32254205911721784), (158536, 0.26950409587439383), (202557, 0.26023809814653576), (272660, 0.1875930563964578), (158082, 0.16062563863528212), (156808, 0.09421911878204836), (162655, 0.0938444249093069), (156624, 0.08042054203791298)]
[(160974, 0.23413413416061818), (158536, 0.1727678342963056), (162655, 0.16474957015923192), (162300, 0.11387862675004873), (156624, 0.08042054203791298), (166283, 0.06770619354744825), (157332, 0.0671423427227867), (161858, 0.061212749824087684), (156560, 0.0594394410523312), (300470, 0.05277661618112871)]
[(300470, 0.3928670049219328), (225463, 0.3430818169208404), (162300, 0.26146625459310563), (202557, 0.26023809814653576), (272660, 0.1875930563964578), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.07949171330613487)]
[(160974, 0.21585021382334774), (158536, 0.0729112529233021), (160417, 0.06107580452411221), (158082, 0.05280282222593651), (16129, 0.045616040769757886), (225463, 0.04417674164898341), (162655, 0.042258003519612335), (300470, 0.04039178416898079), (202557, 0.040167062559711204), (156808, 0.03949103290283185)]
[(202557, 0.40070046087945865), (225463, 0.3877041168750477), (59758, 0.2699743110807744), (162300, 0.26146625459310563), (158536, 0.22092988066584912), (160417, 0.19692143668878087), (272660, 0.13800547097126564), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.07949171330613487)]
[(300470, 0.30295703974562765), (162300, 0.2887614667466498), (160417, 0.25455792387451), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.1523440445824138), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (166283, 0.09179702964358943)]
[(362693, 0.45511961331341866), (308626, 0.32181816482491765), (62599, 0.26276343125998064), (160974, 0.24111815158731453), (202557, 0.14046236273292292), (225463, 0.10758166706668083), (16129, 0.08257752929398565), (272660, 0.07848293595695409), (59758, 0.06917132404063263), (158536, 0.061838888158313135)]
[(95930, 0.21882291446196295), (96481, 0.16090908241245883), (191490, 0.14228035110431095), (123434, 0.14228035110431095), (363291, 0.12847458559243768), (59758, 0.12807052138214622), (16612, 0.12112700091005896), (13938, 0.12112700091005896), (76350, 0.11436795001164322), (284844, 0.11097671047150096)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (182513, 0.12241980393274354), (336476, 0.11639602986490896)]

 90%|████████▉ | 6932/7721 [00:01<00:00, 4850.07it/s]

[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(300470, 0.4014764348351241), (16129, 0.35730069788632535), (162300, 0.32110275999644333), (158536, 0.26950409587439383), (202557, 0.22788352317329924), (59758, 0.18833970444528786), (158082, 0.16062563863528212), (156808, 0.09421911878204836), (162655, 0.0938444249093069), (156624, 0.08042054203791298)]
[(202557, -91), (162655, -92), (158536, -93), (199198, -94), (160417, -95), (16129, -96), (156624, -97), (300470, -98), (272143, -99), (160974, -100)]
[(16129, 0.35730069788632535), (300470, 0.34869981865399535), (162300, 0.2600269554723311), (202557, 0.22788352317329924), (59758, 0.18833970444528786), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.066209620404158)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(355864, 0.32181816482491765), (160974, 0.2456108646206428), (160417, 0.20425752827616475), (184218, 0.16129820911147802), (202675, 0.1461549567508989), (203218, 0.13342061117276546), (158082, 0.13325987617937277), (156624, 0.12312661327811347), (39857, 0.12022458674074696), (300470, 0.11753131362866248)]
[(16129, 0.35730069788632535), (300470, 0.34869981865399535), (162300, 0.2600269554723311), (202557, 0.22788352317329924), (59758, 0.18833970444528786), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.066209620404158)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (236400, 0.1735973656845509), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (237092, 0.15313165267808915), (160417, 0.14414482050765215), (2303, 0.13931112187139225)]
[(160974, 0.24111815158731453), (202557, 0.18742008222688575), (225463, 0.10758166706668083), (107226, 0.08621751937076709), (16129, 0.08257752929398565), (272660, 0.07848293595695409), (320249, 0.07340916583712999), (59758, 0.06917132404063263), (234493, 0.06539414727371758), (158536, 0.061838888158313135)]
[(158536, 0.43421237844128535), (300470, 0.334286551937424), (16129, 0.29379268468323905), (225463, 0.21517513748450606), (202557, 0.21353050149075908), (158082, 0.21342846086121864), (162655, 0.18008352859157967), (156808, 0.1337101516848802), (59758, 0.12538033733281437), (156624, 0.08042054203791298)]
[(160974, 0.4144815905183624), (16129, 0.16945218850947352), (225463, 0.16210175130893217), (272660, 0.07848293595695409), (59758, 0.06917132404063263), (158536, 0.061838888158313135), (298310, 0.05896453910899386), (162655, 0.05569242547034934), (160417, 0.05277661618112871), (225055, 0.04695771949396283)]
[(300470, 0.31960108754426864), (16129, 0.3076991789277927), (59758, 0.2534508587149606), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (284844, 0.11097671047150096), (313504, 0.10798741594776293)]
[(160974, 0.32763802370042133), (158536, 0.15151619968193042), (160417, 0.1466210410904356), (202557, 0.14046236273292292), (225463, 0.10758166706668083), (16129, 0.08257752929398565), (272660, 0.07848293595695409), (158082, 0.070905145249925), (59758, 0.06917132404063263), (156560, 0.06263948773013987)]
[(160974, 0.4121165474228372), (202557, 0.19498244697517428), (16129, 0.19170158326682984), (59758, 0.13213069115310613), (272660, 0.07848293595695409), (96812, 0.066209620404158), (158536, 0.061838888158313135), (298310, 0.05896453910899386), (162655, 0.05569242547034934), (160417, 0.05277661618112871)]
[(16129, 0.3307541732074668), (202557, 0.3138258016639708), (158536, 0.3106071921894664), (160417, 0.29076586159808776), (225463, 0.2785800629022035), (162300, 0.21585021382334774), (59758, 0.19455166137344698), (158082, 0.16089445890289103), (156808, 0.09421911878204836), (272660, 0.07848293595695409)]
[(300470, 0.4342165918837105), (162300, 0.34983727127076203), (16129, 0.3076991789277927), (59758, 0.2534508587149606), (158082, 0.22298036956472989), (162655, 0.1835217364329242), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (166283, 0.15950322319103769), (156624, 0.15323263061577236)]
[(272143, 0.2742467191433369), (16129, 0.24817664391348115), (300470, 0.24111815158731453), (64329, 0.2205925817690975), (162300, 0.21585021382334774), (175040, 0.1845285420073168), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (198659, 0.16133250919593656), (158536, 0.159090992507536)]
[(160974, 0.48672901620795733), (160417, 0.25703414445729345), (202557, 0.14046236273292292), (2303, 0.13931112187139225), (158082, 0.13325987617937277), (156624, 0.12312661327811347), (225463, 0.10758166706668083), (36161, 0.10310208986501465), (166283, 0.09179702964358943), (16129, 0.08257752929398565)]
[(160974, 0.4144815905183624), (16129, 0.16945218850947352), (225463, 0.16210175130893217), (272660, 0.07848293595695409), (59758, 0.06917132404063263), (158536, 0.061838888158313135), (298310, 0.05896453910899386), (162655, 0.05569242547034934), (160417, 0.05277661618112871), (225055, 0.04695771949396283)]
[(160974, 0.159090992507536), (160417, 0.11041310336685785), (166283, 0.09179702964358943), (162655, 0.08967731152361727), (162300, 0.0729112529233021), (156624, 0.07281208857785937), (161858, 0.0706541780456455), (158082, 0.06235473092944776), (300470, 0.061838888158313135), (160894, 0.04698826356216995)]
[(16129, 0.3307541732074668), (202557, 0.3138258016639708), (160417, 0.3073345400556387), (162300, 0.2887614667466498), (225463, 0.2785800629022035), (59758, 0.19455166137344698), (158082, 0.1523440445824138), (162655, 0.1453697369939666), (156808, 0.09421911878204836), (166283, 0.09179702964358943)]
[(76002, 0.4046001915365024), (75999, 0.4046001915365024), (235230, 0.027732739998524172), (182513, 0.01635148984482545), (160417, 0.016154134057464267), (16129, -96), (156624, -97), (300470, -98), (272143, -99), (160974, -100)]
[(16129, 0.35730069788632535), (300470, 0.34869981865399535), (162300, 0.2600269554723311), (202557, 0.22788352317329924), (59758, 0.18833970444528786), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.066209620404158)]
[(160974, 0.4144815905183624), (16129, 0.16945218850947352), (225463, 0.16210175130893217), (272660, 0.07848293595695409), (59758, 0.06917132404063263), (158536, 0.061838888158313135), (298310, 0.05896453910899386), (162655, 0.05569242547034934), (160417, 0.05277661618112871), (225055, 0.04695771949396283)]
[(300470, 0.3236956808813002), (225463, 0.28012244980836687), (162300, 0.26146625459310563), (202557, 0.26023809814653576), (59758, 0.2008029870401418), (158536, 0.159090992507536), (87203, 0.1547920370316812), (236688, 0.14632377139110722), (160417, 0.14414482050765215), (220466, 0.14377949994243003)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(300470, 0.29389476776844325), (162300, 0.27692601834745995), (158536, 0.26950409587439383), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.16062563863528212), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (162655, 0.0938444249093069)]
[(16129, 0.35730069788632535), (300470, 0.34869981865399535), (162300, 0.2600269554723311), (202557, 0.22788352317329924), (59758, 0.18833970444528786), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.066209620404158)]
[(64329, 0.4179510268801069), (198659, 0.40951776217458025), (175040, 0.33285043839602585), (160974, 0.32763802370042133), (156560, 0.16687834618269967), (158536, 0.15151619968193042), (336476, 0.1486341379702074), (160417, 0.1466210410904356), (348111, 0.14077984880864058), (202557, 0.14046236273292292)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(16129, 0.29379268468323905), (300470, 0.28150993575629535), (158536, 0.23200224543083808), (225463, 0.21517513748450606), (202557, 0.21353050149075908), (160417, 0.20522062503176436), (158082, 0.14279213587890255), (156808, 0.1337101516848802), (59758, 0.12538033733281437), (162655, 0.042258003519612335)]
[(16129, 0.3307541732074668), (202557, 0.3138258016639708), (225463, 0.2785800629022035), (158536, 0.22092988066584912), (162300, 0.21585021382334774), (160417, 0.19692143668878087), (59758, 0.19455166137344698), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (272660, 0.07848293595695409)]
[(202557, -91), (162655, -92), (158536, -93), (199198, -94), (160417, -95), (16129, -96), (156624, -97), (300470, -98), (272143, -99), (160974, -100)]
[(300470, 0.34334882391460847), (160417, 0.3156337283986222), (16129, 0.29379268468323905), (225463, 0.21517513748450606), (202557, 0.21353050149075908), (158082, 0.20514686680835031), (156808, 0.1337101516848802), (162655, 0.1319353150432296), (59758, 0.12538033733281437), (166283, 0.09179702964358943)]
[(300470, 0.38158051432023743), (16129, 0.335051303128969), (162300, 0.26865303604928426), (225463, 0.225518480077774), (158536, 0.22144572343698377), (160417, 0.21478114548996824), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (162655, 0.070905145249925), (161858, 0.061212749824087684)]
[(43002, 0.19648335830400424), (273464, 0.19648335830400424), (160974, 0.16723894062155636), (160417, 0.11041310336685785), (166283, 0.09179702964358943), (162655, 0.08967731152361727), (161169, 0.0802139951322084), (161409, 0.07301493326732389), (162300, 0.0729112529233021), (156624, 0.07281208857785937)]
[(183901, 0.4164701851078906), (182628, 0.3110678180600965), (182106, 0.2944888920518062), (316168, 0.15207340994129584), (181928, 0.12872726592996706), (195842, 0.10753213940765202), (206402, 0.05169811407586082), (32459, 0.04808983469629878), (300470, 0.020436024497617927), (254489, 0.014840845185524284)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(300470, 0.29389476776844325), (162300, 0.27692601834745995), (158536, 0.26950409587439383), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.16062563863528212), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (162655, 0.0938444249093069)]
[(160974, 0.32763802370042133), (158536, 0.15151619968193042), (160417, 0.1466210410904356), (202557, 0.14046236273292292), (2303, 0.13931112187139225), (225463, 0.10758166706668083), (36161, 0.10310208986501465), (16129, 0.08257752929398565), (36129, 0.08028034417637815), (272660, 0.07848293595695409)]
[(83572, 0.19742467821773158), (84721, 0.1860368755170824), (213927, 0.11550804670065219), (83739, 0.1018965932484866), (236400, 0.09363530795694984), (84916, 0.08936922424865167), (107069, 0.07594923639308739), (106783, 0.07594923639308739), (207035, 0.07503075613170705), (205879, 0.06793106216565774)]
[(270847, 0.26276343125998064), (313504, 0.1472526015546704), (59758, 0.12807052138214622), (236613, 0.11534695013967687), (272312, 0.11343971980809854), (331242, 0.11334882739964329), (284844, 0.11097671047150096), (160974, 0.08089758512742111), (235669, 0.0801497244938313), (300470, 0.07848293595695409)]
[(300470, 0.29389476776844325), (162300, 0.27692601834745995), (158536, 0.26950409587439383), (16129, 0.24817664391348115), (202557, 0.18669866433988613), (225463, 0.18579832160874798), (158082, 0.16062563863528212), (59758, 0.12538033733281437), (207022, 0.120386881724791), (156808, 0.09421911878204836)]
[(160974, 0.30323581301518815), (162655, 0.1835217364329242), (166283, 0.15950322319103769), (156624, 0.15323263061577236), (162300, 0.1339870574474143), (158082, 0.13299105591176386), (300470, 0.11461550433944184), (161858, 0.0706541780456455), (157332, 0.0671423427227867), (156560, 0.0594394410523312)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(16129, 0.3307541732074668), (202557, 0.3138258016639708), (225463, 0.2785800629022035), (158536, 0.22092988066584912), (162300, 0.21585021382334774), (160417, 0.19692143668878087), (59758, 0.19455166137344698), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (272660, 0.07848293595695409)]
[(162300, 0.26865303604928426), (16129, 0.24817664391348115), (300470, 0.24111815158731453), (158536, 0.22144572343698377), (160417, 0.21478114548996824), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (162655, 0.070905145249925)]
[(300470, 0.48916218138691825), (16129, 0.4441753571018132), (162300, 0.2600269554723311), (59758, 0.18833970444528786), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.066209620404158), (225499, 0.0476500173121018)]
[(338823, 0.6436363296498353), (160974, 0.24817664391348115), (225463, 0.1091240539728442), (202557, 0.08687465921548786), (300470, 0.08257752929398565), (96812, 0.07949171330613487), (260931, 0.07576702839157815), (59758, 0.07542264970732743), (272660, 0.05952253501431156), (162300, 0.045616040769757886)]
[(274915, 0.2082350925539453), (68887, 0.15109311015596852), (331242, 0.12022458674074694), (209294, 0.09555967337031585), (212165, 0.09248495777029786), (331187, 0.0802511056697833), (50626, 0.07417483657581951), (119044, 0.06532825241206365), (273394, 0.06532825241206365), (206159, 0.06532825241206365)]
[(160974, 0.32201573671473566), (59758, 0.19724184542277884), (158535, 0.15170653777113954), (297628, 0.15170653777113954), (234616, 0.15170653777113954), (16129, 0.14210006430829722), (202557, 0.14046236273292292), (156025, 0.13851934657921303), (236613, 0.12609435157441656), (218413, 0.12022458674074694)]
[(16129, 0.439878227180311), (162300, 0.3940140129197454), (202557, 0.36834588590622214), (59758, 0.2575110284859205), (162655, 0.23921416190327352), (158082, 0.22298036956472989), (166283, 0.15950322319103769), (156624, 0.15323263061577236), (156808, 0.09421911878204836), (272660, 0.07848293595695409)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (155023, 0.09734545040003979), (158082, 0.08998931365296603)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(300470, 0.3859921002678558), (16129, 0.3692153343905665), (225463, 0.2781345045969796), (158536, 0.23200224543083808), (202557, 0.21353050149075908), (119592, 0.21094598884529175), (160417, 0.20522062503176436), (273464, 0.14916133917660762), (158082, 0.14279213587890255), (156808, 0.1337101516848802)]
[(206911, 0.16348379121493115), (202528, 0.14767618657002798), (207391, 0.11116215170888447), (316427, 0.10023962764608933), (202684, 0.09473534720724953), (160417, 0.0938444249093069), (16612, 0.09229886699237806), (13938, 0.09229886699237806), (95876, 0.09229886699237806), (96680, 0.09229886699237806)]
[(160974, 0.1733634389310479), (300470, 0.14046236273292292), (16129, 0.08687465921548786), (225463, 0.054520084242251354), (225055, 0.04695771949396283), (202428, 0.04656258378954941), (71502, 0.0446747393161127), (206402, 0.041929988156953264), (355382, 0.041162440681814426), (206661, 0.041051472544304385)]
[(300470, 0.3764722970624289), (162300, 0.32254205911721784), (225463, 0.28012244980836687), (158536, 0.26950409587439383), (202557, 0.26023809814653576), (59758, 0.2008029870401418), (158082, 0.16062563863528212), (156808, 0.09421911878204836), (162655, 0.0938444249093069), (156624, 0.08042054203791298)]
[(160974, 0.24817664391348115), (97485, 0.20882320017436845), (97480, 0.1654884707784808), (95742, 0.11032564718565388), (225463, 0.1091240539728442), (91369, 0.09963398728176989), (96954, 0.09963398728176989), (95680, 0.09053749898732362), (202557, 0.08687465921548786), (91361, 0.08525171448037899)]
[(160974, 0.5475676835498812), (160417, 0.3247403380047417), (202557, 0.14046236273292292), (158082, 0.13325987617937277), (156624, 0.12312661327811347), (161858, 0.11679005889132951), (225463, 0.10758166706668083), (16129, 0.08257752929398565), (272660, 0.07848293595695409), (162300, 0.0729112529233021)]
[(160974, 0.4892947955007957), (202557, 0.22733702194841077), (225463, 0.21670572103952504), (59758, 0.14459397374796007), (272660, 0.13800547097126564), (96812, 0.07949171330613487), (260931, 0.07576702839157815), (158536, 0.061838888158313135), (298310, 0.05896453910899386), (162655, 0.05569242547034934)]
[(236613, 0.16017892526431968), (59758, 0.12807052138214622), (87203, 0.11162212531024944), (284844, 0.11097671047150096), (255486, 0.10201394465967895), (319880, 0.08340647828484926), (320720, 0.08340647828484926), (321723, 0.08340647828484926), (160974, 0.08089758512742111), (114461, 0.08048592087636894)]
[(166215, 0.2147864250446643), (212196, 0.16414788498337793), (158535, 0.15170653777113954), (297628, 0.15170653777113954), (234616, 0.15170653777113954), (156025, 0.13851934657921303), (218413, 0.12022458674074694), (118500, 0.11742126555152319), (157077, 0.10614894711958893), (283552, 0.10355582242660198)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(16129, 0.3307541732074668), (202557, 0.3138258016639708), (225463, 0.2785800629022035), (158536, 0.22092988066584912), (162300, 0.21585021382334774), (160417, 0.19692143668878087), (59758, 0.19455166137344698), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (272660, 0.07848293595695409)]
[(160974, 0.23066469262075895), (158536, 0.20009041489047513), (158082, 0.14154147023224112), (156624, 0.1307350667381671), (156560, 0.12207892878247106), (157332, 0.11230134303368475), (300470, 0.10846904165147805), (166283, 0.06770619354744825), (162300, 0.06107580452411221), (272143, 0.052215875368756395)]

100%|██████████| 7721/7721 [00:01<00:00, 4856.13it/s]

[(160974, 0.25189598096294374), (59758, 0.19102988849461972), (300470, 0.18606460302363492), (16129, 0.16864658898715576), (284844, 0.11097671047150096), (313504, 0.10798741594776293), (96812, 0.066209620404158), (236613, 0.06089593473724781), (273464, 0.05853490036423154), (202557, 0.054520084242251354)]
[(111031, 0.26276343125998064), (352614, 0.1816905013650884), (352461, 0.1816905013650884), (160974, 0.17334377498802903), (202528, 0.14575492688072578), (283933, 0.1367782296577098), (59310, 0.11801902116367535), (57881, 0.11801902116367535), (68922, 0.11801902116367535), (58867, 0.11801902116367535)]
[(160974, 0.3852629720949667), (158536, 0.17225199152517098), (162655, 0.14953685037965625), (202557, 0.14046236273292292), (225463, 0.10758166706668083), (16129, 0.08257752929398565), (156624, 0.08042054203791298), (272660, 0.07848293595695409), (158082, 0.0706363249823161), (59758, 0.06917132404063263)]
[(160974, 0.24817664391348115), (225463, 0.1091240539728442), (202557, 0.08687465921548786), (300470, 0.08257752929398565), (96812, 0.07949171330613487), (260931, 0.07576702839157815), (59758, 0.07542264970732743), (272660, 0.05952253501431156), (162300, 0.045616040769757886), (15152, 0.04151412617727313)]
[(300470, 0.431277347947981), (202557, 0.3147581823887871), (162300, 0.305642996242089), (59758, 0.2637623541526153), (284312, 0.17253766289901798), (158536, 0.159090992507536), (96812, 0.14570133371029287), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(160974, 0.14414482050765215), (158536, 0.11041310336685785), (162655, 0.0938444249093069), (156624, 0.08042054203791298), (158082, 0.0706363249823161), (166283, 0.06770619354744825), (157332, 0.0671423427227867), (162300, 0.06107580452411221), (220258, 0.060853212265398166), (50629, 0.06063608079621973)]
[(16129, 0.29379268468323905), (300470, 0.28150993575629535), (158536, 0.23200224543083808), (225463, 0.21517513748450606), (202557, 0.21353050149075908), (160417, 0.20522062503176436), (158082, 0.14279213587890255), (156808, 0.1337101516848802), (59758, 0.12538033733281437), (162655, 0.042258003519612335)]
[(355838, 0.17517562083998708), (160974, 0.159090992507536), (156628, 0.11957596390830347), (278696, 0.11957596390830347), (284846, 0.11957596390830347), (160417, 0.11041310336685785), (166283, 0.09179702964358943), (232753, 0.09016612023797267), (162655, 0.08967731152361727), (31349, 0.08358001201147049)]
[(160974, 0.5443539646025026), (162655, 0.23921416190327352), (166283, 0.15950322319103769), (156624, 0.15323263061577236), (202557, 0.14046236273292292), (162300, 0.1339870574474143), (158082, 0.13299105591176386), (225463, 0.10758166706668083), (16129, 0.08257752929398565), (272660, 0.07848293595695409)]
[(2303, 0.13931112187139225), (307415, 0.12751743082459868), (78346, 0.10983753640380031), (36161, 0.10310208986501465), (288389, 0.09290090204588879), (208426, 0.0908452506825442), (308166, 0.09016844005556021), (36129, 0.08028034417637815), (129238, 0.07766686681995148), (277174, 0.06423729279621884)]
[(182485, 0.4164701851078906), (160974, 0.32548454817944866), (182106, 0.2944888920518062), (226101, 0.24014991860579388), (215839, 0.24014991860579388), (215770, 0.24014991860579388), (284312, 0.17253766289901798), (220165, 0.1698116359475543), (215641, 0.1698116359475543), (225463, 0.1091240539728442)]
[(300470, 0.29389476776844325), (162300, 0.27692601834745995), (158536, 0.26950409587439383), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.16062563863528212), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (162655, 0.0938444249093069)]
[(300470, 0.2968105770576639), (158536, 0.29316917828599603), (16129, 0.24817664391348115), (160417, 0.23798924541695904), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (338234, 0.1654884707784808), (158082, 0.16089445890289103), (87203, 0.1547920370316812)]
[(300470, 0.31960108754426864), (16129, 0.3076991789277927), (59758, 0.2534508587149606), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (284844, 0.11097671047150096), (313504, 0.10798741594776293)]
[(160974, 0.4144815905183624), (16129, 0.16945218850947352), (225463, 0.16210175130893217), (272660, 0.07848293595695409), (59758, 0.06917132404063263), (158536, 0.061838888158313135), (298310, 0.05896453910899386), (162655, 0.05569242547034934), (160417, 0.05277661618112871), (225055, 0.04695771949396283)]
[(202557, 0.40070046087945865), (225463, 0.3877041168750477), (59758, 0.2699743110807744), (162300, 0.26146625459310563), (158536, 0.22092988066584912), (160417, 0.19692143668878087), (272660, 0.13800547097126564), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.07949171330613487)]
[(160974, 0.4144815905183624), (16129, 0.16945218850947352), (225463, 0.16210175130893217), (272660, 0.07848293595695409), (59758, 0.06917132404063263), (158536, 0.061838888158313135), (298310, 0.05896453910899386), (162655, 0.05569242547034934), (160417, 0.05277661618112871), (225055, 0.04695771949396283)]
[(160974, 0.2380967347135347), (284312, 0.17253766289901798), (16129, 0.1091240539728442), (300470, 0.10758166706668083), (285023, 0.07826243580495225), (293425, 0.07362222301295154), (284629, 0.06851847711140549), (96812, 0.066209620404158), (59758, 0.0629593671124735), (70023, 0.05696192729481554)]
[(300470, 0.2968105770576639), (158536, 0.24876830403115327), (16129, 0.24817664391348115), (160417, 0.23798924541695904), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.16089445890289103), (59758, 0.12538033733281437), (156808, 0.09421911878204836)]
[(300470, 0.2968105770576639), (158536, 0.24876830403115327), (16129, 0.24817664391348115), (160417, 0.23798924541695904), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.16089445890289103), (59758, 0.12538033733281437), (156808, 0.09421911878204836)]
[(160974, 0.4144815905183624), (16129, 0.16945218850947352), (225463, 0.16210175130893217), (272660, 0.07848293595695409), (59758, 0.06917132404063263), (158536, 0.061838888158313135), (298310, 0.05896453910899386), (162655, 0.05569242547034934), (160417, 0.05277661618112871), (225055, 0.04695771949396283)]
[(300470, 0.30295703974562765), (162300, 0.2887614667466498), (160417, 0.25455792387451), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.1523440445824138), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (166283, 0.09179702964358943)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (124263, 0.21667900203254453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836)]
[(300470, 0.3236956808813002), (225463, 0.28012244980836687), (162300, 0.26146625459310563), (202557, 0.26023809814653576), (59758, 0.2008029870401418), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.07949171330613487)]
[(300470, 0.29389476776844325), (162300, 0.27692601834745995), (158536, 0.26950409587439383), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.16062563863528212), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (162655, 0.0938444249093069)]
[(272143, 0.2742467191433369), (64329, 0.2205925817690975), (198659, 0.2174659710834944), (175040, 0.1845285420073168), (182394, 0.1762582590544219), (273395, 0.16461978179963532), (272660, 0.12807052138214622), (160974, 0.12538033733281437), (68887, 0.12007662799870396), (42189, 0.10176783932622224)]
[(158536, 0.311123034960601), (160417, 0.30862557039927513), (300470, 0.2968105770576639), (162300, 0.26865303604928426), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (156560, 0.06263948773013987)]
[(250407, 0.26276343125998064), (97485, 0.20882320017436845), (95856, 0.18580180409177757), (97458, 0.17936394586245522), (97480, 0.1654884707784808), (95742, 0.11032564718565388), (91369, 0.09963398728176989), (96954, 0.09963398728176989), (97600, 0.09290090204588879), (95680, 0.09053749898732362)]
[(355838, 0.17517562083998708), (298639, 0.13154793622888658), (97474, 0.12022458674074694), (156628, 0.11957596390830347), (278696, 0.11957596390830347), (284846, 0.11957596390830347), (232753, 0.09016612023797267), (42422, 0.08501162054973246), (206661, 0.08501162054973246), (31349, 0.08358001201147049)]
[(64329, 0.4179510268801069), (175040, 0.33285043839602585), (160974, 0.23998857763495712), (182394, 0.1941529153368664), (156560, 0.16277583453331607), (156624, 0.15807701387440037), (324823, 0.14920713485641457), (336476, 0.1486341379702074), (348111, 0.14077984880864058), (300470, 0.14032182411526722)]
[(160974, 0.30195681892923837), (158536, 0.15363591780190256), (202557, 0.14046236273292292), (160417, 0.12048280972857696), (225463, 0.10758166706668083), (162655, 0.09967352563300977), (16129, 0.08257752929398565), (272660, 0.07848293595695409), (59758, 0.06917132404063263), (298310, 0.05896453910899386)]
[(160974, 0.08998931365296603), (162655, 0.070905145249925), (160417, 0.0706363249823161), (158536, 0.06235473092944776), (161858, 0.061212749824087684), (162300, 0.05280282222593651), (236802, 0.05100697232983947), (210994, 0.05100697232983947), (283835, 0.05100697232983947), (31632, 0.04551196133134187)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(300470, 0.3855345690396133), (162300, 0.3343775075164077), (225463, 0.28012244980836687), (202557, 0.26023809814653576), (160417, 0.25455792387451), (59758, 0.2008029870401418), (158082, 0.1523440445824138), (156808, 0.09421911878204836), (166283, 0.09179702964358943), (162655, 0.08967731152361727)]
[(160974, 0.24111815158731453), (202557, 0.14046236273292292), (225463, 0.10758166706668083), (16129, 0.08257752929398565), (272660, 0.07848293595695409), (59758, 0.06917132404063263), (158536, 0.061838888158313135), (298310, 0.05896453910899386), (162655, 0.05569242547034934), (160417, 0.05277661618112871)]
[(300470, 0.375293513014618), (16129, 0.3076991789277927), (59758, 0.2534508587149606), (158536, 0.24876830403115327), (160417, 0.23798924541695904), (162300, 0.21585021382334774), (355838, 0.17517562083998708), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.16089445890289103)]
[(300470, 0.3236956808813002), (225463, 0.28012244980836687), (162300, 0.26146625459310563), (202557, 0.26023809814653576), (59758, 0.2008029870401418), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.07949171330613487)]
[(342100, 0.17729997979489165), (160974, 0.159090992507536), (59310, 0.13627662727668824), (57881, 0.13627662727668824), (68922, 0.13627662727668824), (58867, 0.13627662727668824), (59237, 0.13627662727668824), (168701, 0.13627662727668824), (167289, 0.13627662727668824), (160417, 0.11041310336685785)]
[(160974, 0.30583952747631377), (158536, 0.13526598385274985), (160417, 0.1317121295064283), (162655, 0.11316314876953734), (161858, 0.061212749824087684), (236802, 0.05100697232983947), (210994, 0.05100697232983947), (283835, 0.05100697232983947), (16129, 0.045616040769757886), (31632, 0.04551196133134187)]
[(300470, 0.29389476776844325), (162300, 0.27692601834745995), (158536, 0.26950409587439383), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.16062563863528212), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (162655, 0.0938444249093069)]
[(160974, 0.23066469262075895), (158536, 0.20009041489047513), (158082, 0.14154147023224112), (156624, 0.1307350667381671), (156560, 0.12207892878247106), (157332, 0.11230134303368475), (300470, 0.10846904165147805), (166283, 0.06770619354744825), (162300, 0.06107580452411221), (272143, 0.052215875368756395)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(300470, 0.3236956808813002), (225463, 0.28012244980836687), (162300, 0.26146625459310563), (202557, 0.26023809814653576), (59758, 0.2008029870401418), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.07949171330613487)]
[(160974, 0.4121165474228372), (202557, 0.19498244697517428), (16129, 0.19170158326682984), (59758, 0.13213069115310613), (272660, 0.07848293595695409), (96812, 0.066209620404158), (158536, 0.061838888158313135), (298310, 0.05896453910899386), (162655, 0.05569242547034934), (160417, 0.05277661618112871)]
[(16129, 0.3235992936208086), (300470, 0.3102894756279472), (225463, 0.23395776294799614), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (158536, 0.159090992507536), (160417, 0.14414482050765215), (272660, 0.12807052138214622), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(16129, 0.3307541732074668), (202557, 0.3138258016639708), (158536, 0.3106071921894664), (160417, 0.29076586159808776), (225463, 0.2785800629022035), (162300, 0.21585021382334774), (59758, 0.19455166137344698), (158082, 0.16089445890289103), (156808, 0.09421911878204836), (272660, 0.07848293595695409)]
[(300470, 0.2968105770576639), (158536, 0.24876830403115327), (16129, 0.24817664391348115), (160417, 0.23798924541695904), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.16089445890289103), (59758, 0.12538033733281437), (156808, 0.09421911878204836)]
[(16129, 0.35730069788632535), (300470, 0.34869981865399535), (162300, 0.2600269554723311), (202557, 0.22788352317329924), (59758, 0.18833970444528786), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.066209620404158)]
[(160974, 0.3082164904653266), (175040, 0.2415397583322196), (199198, 0.2205925817690975), (272143, 0.19735844511100942), (284312, 0.17253766289901798), (202557, 0.14046236273292292), (225463, 0.10758166706668083), (16129, 0.08257752929398565), (272660, 0.07848293595695409), (285023, 0.07826243580495225)]
[(300470, 0.29389476776844325), (162300, 0.27692601834745995), (158536, 0.26950409587439383), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.16062563863528212), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (162655, 0.0938444249093069)]
[(16129, 0.439878227180311), (202557, 0.36834588590622214), (162300, 0.2600269554723311), (59758, 0.2575110284859205), (158536, 0.22092988066584912), (160417, 0.19692143668878087), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (272660, 0.07848293595695409), (96812, 0.066209620404158)]
[(297628, 0.15170653777113954), (234616, 0.15170653777113954), (156025, 0.13851934657921303), (218413, 0.12022458674074694), (157077, 0.10614894711958893), (283552, 0.10355582242660198), (161585, 0.09614217107901918), (78374, 0.07585326888556977), (161169, 0.06851885073526995), (160974, -100)]
[(300470, 0.3236956808813002), (225463, 0.28012244980836687), (162300, 0.26146625459310563), (202557, 0.26023809814653576), (59758, 0.2008029870401418), (158536, 0.159090992507536), (160417, 0.14414482050765215), (156808, 0.09421911878204836), (158082, 0.08998931365296603), (96812, 0.07949171330613487)]
[(300470, 0.358649465215977), (160417, 0.3484023487838169), (162300, 0.2887614667466498), (16129, 0.24817664391348115), (158082, 0.2232491898323388), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (59758, 0.12538033733281437), (156624, 0.12312661327811347), (156808, 0.09421911878204836)]
[(160974, 0.14414482050765215), (211692, 0.120386881724791), (158536, 0.11041310336685785), (162655, 0.0938444249093069), (33333, 0.08409891893565574), (156624, 0.08042054203791298), (158082, 0.0706363249823161), (166283, 0.06770619354744825), (157332, 0.0671423427227867), (162300, 0.06107580452411221)]
[(300470, 0.29389476776844325), (162300, 0.27692601834745995), (158536, 0.26950409587439383), (16129, 0.24817664391348115), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158082, 0.16062563863528212), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (162655, 0.0938444249093069)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(160974, 0.41917503974900383), (300470, 0.19015919636066647), (96812, 0.14570133371029287), (202557, 0.14139474345773922), (59758, 0.13838201681980095), (162300, 0.0897927824187413), (260931, 0.07576702839157815), (272660, 0.05952253501431156), (225499, 0.0476500173121018), (219917, 0.04568359724402418)]
[(285112, 0.17002324109946493), (352614, 0.12112700091005896), (352461, 0.12112700091005896), (321020, 0.11334882739964329), (32486, 0.09254893002397568), (353593, 0.08564972372829179), (118357, 0.07322502426920022), (13811, 0.053433149662554205), (107039, 0.05281743697670902), (352116, 0.04750991855872012)]
[(16129, 0.24817664391348115), (300470, 0.24111815158731453), (162300, 0.21585021382334774), (202557, 0.1733634389310479), (225463, 0.17099839583552265), (158536, 0.159090992507536), (160417, 0.14414482050765215), (59758, 0.12538033733281437), (156808, 0.09421911878204836), (158082, 0.08998931365296603)]
[(160974, 0.32763802370042133), (158536, 0.15151619968193042), (129364, 0.1481206605975723), (160417, 0.1466210410904356), (202557, 0.14046236273292292), (191078, 0.10767730045434391), (225463, 0.10758166706668083), (275190, 0.09783754481180722), (226101, 0.08769035173561526), (215839, 0.08769035173561526)]
[(160974, 0.24111815158731453), (202557, 0.14046236273292292), (225463, 0.10758166706668083), (16129, 0.08257752929398565), (272660, 0.07848293595695409), (59758, 0.06917132404063263), (158536, 0.061838888158313135), (298310, 0.05896453910899386), (162655, 0.05569242547034934), (160417, 0.05277661618112871)]
[(160974, 0.25331734355275026), (284312, 0.22308055842882293), (272660, 0.12807052138214622), (158536, 0.09179702964358943), (285023, 0.07826243580495225), (16129, 0.07542264970732743), (293425, 0.07362222301295154), (300470, 0.06917132404063263), (284629, 0.06851847711140549), (160417, 0.06770619354744825)]

In [55]:
user_item_score_list=[]
# 转换为DataFrame查看
for user,memo in user_recall_items_dict.items():
    for item,score in memo:
        user_item_score_list.append([user,item,score])
recall_df=pd.DataFrame(user_item_score_list,columns=['user_id','click_article_id','pred_score'])
recall_df.head()

   user_id  click_article_id  pred_score
0   199999            107301    0.178689
1   199999             50864    0.150742
2   199999            160974    0.144145
3   199999             50383    0.135146
4   199999            158536    0.110413

In [ ]:
def submit(user_recall_items_dict,model_name=None):
    '''生成提交文件'''
    ans=[]
    for user,memo in user_recall_items_dict.items():
        tmp=[]
        # 按照得分降序排列
        for item,score in sorted(memo,key=lambda x:x[1],reverse=True):
            tmp.append(item)
        ans.append([[user]+tmp[:]])
    ans=pd.DataFrame(ans,columns=['user_id', 'article_1', 'article_2','article_3', 'article_4', 'article_5'])
    ans.to_csv('./save/submission.csv',index=False,header=True)